Componente Chips: stesura e revisione contenuti
italia/designers.italia.it pull request #1000
Opened 2023-10-10 15:14 UTC by Fupete

2023-10-16 15:52 UTC, Fupete commented
@danielaiozzo @zetareticoli devo ancora buttar giù un paio di paragrafi "Comportamento/Interazione" ma intanto potreste far review di quel che c'è. A domani.

2023-10-17 08:27 UTC, danielaiozzo requested changes

2023-10-17 08:27 UTC, danielaiozzo commented on src/data/content/design-system/componenti/chips.yaml
> +  description: "Il componente Chips permette di etichettare, classificare e organizzare contenuti ed elementi dell'interfaccia utilizzando parole chiave (tag), stati o altri attributi per abilitare p
```suggestion
  description: "Il componente Chips permette di etichettare, classificare e organizzare contenuti o elementi di interfaccia mediante parole chiave (tag), stati o altri attributi per abilitare percorsi di navigazione trasversale, filtri o scelte dell'utente."
```

2023-10-17 08:27 UTC, danielaiozzo commented on src/data/content/design-system/componenti/chips.yaml
> +  description: "Il componente Chips permette di etichettare, classificare e organizzare contenuti ed elementi dell'interfaccia utilizzando parole chiave (tag), stati o altri attributi per abilitare p
@Fupete ho revisionato in "contenuti o elementi" invece di "contenuti e elementi", valuta tu se è corretto cmque

2023-10-17 08:27 UTC, danielaiozzo commented on src/data/content/design-system/componenti/chips.yaml
> +              Usa il componente per classificare e organizzare contenuti e parti dell'interfaccia a seconda di tag, stati, utenti o altre ontologie utili al contesto; per dare accesso diretto ad arch
```suggestion
              Usa il componente per classificare e organizzare contenuti e parti dell'interfaccia in base a liste di tag, stati, utenti o altre ontologie legate al contesto; puoi usarlo inoltre per dare accesso diretto ad archivi di contenuti filtrati per attributi o per permettere all'utente di selezionare o rimuovere scelte di input (ad esempio filtri per attributo o utenti destinatari di un messaggio).      
```

2023-10-17 08:27 UTC, danielaiozzo commented on src/data/content/design-system/componenti/chips.yaml
> +              - Considera che il componente è visivamente riconoscibile come interattivo, per etichette statiche valuta l'uso del componente Badge.
```suggestion
              - Tieni presente che il componente è visivamente riconoscibile come interattivo; per etichette statiche valuta quindi l'uso del componente Badge.  
```

2023-10-17 08:27 UTC, danielaiozzo commented on src/data/content/design-system/componenti/chips.yaml
> +              - Considera che il componente è visivamente riconoscibile come interattivo, per etichette statiche valuta l'uso del componente Badge.
qui se è buona pratica l'uso di badge come componenti per etichette statiche forse rafforzerei il suggerimento. altrimenti va bene così. credo cmque che badge vada linkato come più avanti

2023-10-17 08:27 UTC, danielaiozzo commented on src/data/content/design-system/componenti/chips.yaml
> +              - Usa chips rimuovibili per scelte: l'utente può rimuovere il filtro se lo ritiene.
```suggestion
              - Usa chips rimovibili per le scelte: l'utente potrà rimuovere il filtro se utile. 
```

2023-10-17 08:27 UTC, danielaiozzo commented on src/data/content/design-system/componenti/chips.yaml
> +              - L'uso di molti componenti di questo tipo sulla stessa pagina può aumentare molto la quantità di rumore visivo sullo schermo, in particolare se combinato con altri elementi visivi, qui
```suggestion
              - L'uso di numerosi componenti di questo tipo sulla stessa pagina può aumentare il carico cognitivo per l'utente, in particolare se combinato con altri elementi visivi: usa quindi tali componenti con moderazione.
```

2023-10-17 08:27 UTC, danielaiozzo commented on src/data/content/design-system/componenti/chips.yaml
> +              - Le chips colorate possono essere utilizzate per organizzare una grande quantità di contenuti: ad esempio utilizzando etichette per organizzare le segnalazioni per argomento in una lun
```suggestion
              - Le chips colorate possono essere utilizzate per organizzare una grande quantità di contenuti: ad esempio potresti usare le etichette per organizzare le segnalazioni per argomento in una lunga lista di segnalazioni. 
```

2023-10-17 08:27 UTC, danielaiozzo commented on src/data/content/design-system/componenti/chips.yaml
> +              - Configura la parte interattiva del componente scegliendo i corretti elementi `HTML`: utilizza `<button>` laddove si configuri una azione (ad esempio selezione filtro), e `<a>` laddove
```suggestion
              - Configura la parte interattiva del componente scegliendo i corretti elementi `HTML`: usa `<button>` dove è possibile un'azione (ad esempio selezione filtro), e `<a>` dove il componente facilita la navigazione (ad esempio link a un archivio filtrato).  
```

2023-10-17 08:27 UTC, danielaiozzo commented on src/data/content/design-system/componenti/chips.yaml
> +              - Usa chips disabilitate con moderazione, assicurandoti che per l’utente sia chiaro come attivarle.
```suggestion
              - Usa chips disabilitate con moderazione, assicurandoti che all’utente sia chiaro come attivarle.
```

2023-10-17 08:27 UTC, danielaiozzo commented on src/data/content/design-system/componenti/chips.yaml
> +              5. **icona rimozione**: opzionale, utile per i casi di utilizzo del componente come input di scelta.
```suggestion
              5. **icona rimozione**: opzionale, utile nell'uso del componente come input di scelta.
```

2023-10-17 13:35 UTC, danielaiozzo requested changes

2023-10-17 13:35 UTC, danielaiozzo commented on src/data/content/design-system/componenti/chips.yaml
> +              Il click sull'icona di rimozione, laddove presente, eliminerà il componente.
```suggestion
              Il click sull'icona di rimozione, laddove presente, eliminerà la visualizzazione del componente.
```

2023-10-17 14:22 UTC, danielaiozzo approved these changes

2023-10-17 14:44 UTC, merged