Componente Video player: stesura e revisione contenuti
italia/designers.italia.it pull request #1003
Opened 2023-10-10 15:19 UTC by Fupete

2023-10-19 14:46 UTC, Fupete commented
Componente Video player: definizione immagini anatomia e specifiche di design

Da fare a valle della risoluzione di https://github.com/italia/design-ui-kit/issues/100

2023-10-19 14:51 UTC, Fupete commented on src/data/content/design-system/componenti/video-player.yaml
> +              Per mostrare video nelle pagine del proprio sito. È possibile utilizzarlo per video caricati nel proprio hosting o per video provenienti da piattaforme di terze parti.
```suggestion
              Il componente Videoplayer è utile per mostrare video nelle pagine del proprio sito. È possibile utilizzarlo per video caricati nel proprio hosting o per video provenienti da piattaforme di terze parti attivando la variante con overlay di consenso.  
              
              I video possono essere strumenti molto importanti sia dal punto di vista della comunicazione che dell'istruzione. È importante fare particolare attenzione e valutare gli aspetti di privacy e accessibilità dei contenuti prima del loro uso, magari coinvolgendo esperti di settore e responsabili della privacy del proprio ente o progetto.    
```

2023-10-19 16:49 UTC, Fupete commented on src/data/content/design-system/componenti/video-player.yaml
> +              Il componente video player è utile per mostrare video nelle pagine del proprio sito. È possibile utilizzarlo per video caricati nel proprio hosting o per video provenienti da piattaform
```suggestion
              Il componente video player è utile per mostrare video nelle pagine del proprio sito. È possibile utilizzarlo per video caricati nel proprio hosting o per video incorporati da piattaforme di terze parti attivando la variante con overlay di consenso.  
```

2023-10-19 16:51 UTC, Fupete commented on src/data/content/design-system/componenti/video-player.yaml
> +              - Carica nei parametri del video player i sottotitoli (ad esempio fornendo l'url di un file in formato `.vtt`)
```suggestion
              - Carica nei parametri del video player i sottotitoli in formato [WebVTT](https://www.w3.org/TR/webvtt1/)
```

2023-10-19 16:52 UTC, Fupete commented on src/data/content/design-system/componenti/video-player.yaml
> +              - Devi fornire sottotitoli e trascrizioni come da normativa sull'accessibilità. Ti ricordiamo che i soli sottotitoli generati in automatico da una piattaforma non sono sufficienti, se n
```suggestion
              - Ti ricordiamo che i soli sottotitoli generati in automatico da una piattaforma non sono sufficienti, se non controllati ed eventualmente corretti o integrati da un umano.
```

2023-10-19 16:54 UTC, Fupete commented on src/data/content/design-system/componenti/video-player.yaml
> +              - ...
```suggestion
              - Mostra video che rispondano a bisogni dell'utente, ad esempio semplificando l'accesso ad informazioni o fornendo istruzioni su come svolgere attività.
              - ... 
```

2023-10-19 16:57 UTC, Fupete commented
@danielaiozzo prima bozza pronta per review. 
@astagi vedi qualcosa che si può aggiungere lato contenuto?

2023-10-19 16:57 UTC, danielaiozzo requested changes

2023-10-19 16:57 UTC, danielaiozzo commented on src/data/content/design-system/componenti/video-player.yaml
> +              Il componente video player è utile per mostrare video nelle pagine del proprio sito. È possibile utilizzarlo per video caricati nel proprio hosting o per video provenienti da piattaform
```suggestion
              Il componente video player è utile per mostrare video nelle pagine del proprio sito. Si può usare per video caricati su un hosting proprio oppure per video provenienti da piattaforme di terze parti, attivando la variante con overlay di consenso.  
```

2023-10-19 16:57 UTC, danielaiozzo commented on src/data/content/design-system/componenti/video-player.yaml
> +              I video possono essere strumenti molto importanti sia dal punto di vista della comunicazione che dell'istruzione. È importante fare particolare attenzione e valutare gli aspetti di priv
```suggestion
              I video possono essere strumenti preziosi sia dal punto di vista della comunicazione che dell'istruzione. È però importante valutare e curare gli aspetti di privacy e accessibilità dei contenuti prima di pubblicarli, di preferenza tenendo conto del parere di esperti di settore e responsabili della privacy del proprio ente o progetto.    
```

2023-10-19 16:57 UTC, danielaiozzo commented on src/data/content/design-system/componenti/video-player.yaml
> +              - Implementa il meccanismo di gestione overlay del consenso ogniqualvolta utilizzi video provenienti da piattaforme di terze parti (ad esempio Youtube).
```suggestion
              - Implementa il meccanismo di gestione overlay del consenso ogni volta che usi video provenienti da piattaforme di terze parti (ad esempio YouTube). 
```

2023-10-19 16:57 UTC, danielaiozzo commented on src/data/content/design-system/componenti/video-player.yaml
> +              - Non forzare il player in modalità "auto-play", lascia all'utente la facoltà di farlo iniziare, mettere in pausa o interrompere.
```suggestion
              - Non forzare il player in modalità "auto-play": lascia all'utente la scelta di farlo iniziare, mettere in pausa o interrompere la visione.
```

2023-10-19 16:57 UTC, danielaiozzo commented on src/data/content/design-system/componenti/video-player.yaml
> +              - Se utilizzi video provenienti da piattaforme di terze parti dovrai collegare la tua Cookie Policy nel meccanismo di overlay, aggiornare la stessa cookie policy con l'aiuto del Respons
```suggestion
              - Se utilizzi video provenienti da piattaforme di terze parti dovrai collegare la tua cookie policy nel meccanismo di overlay del consenso, aggiornare la stessa cookie policy con l'aiuto del responsabile del trattamento dati del tuo ente e implementare un meccanismo per la revoca del consenso, simile ad esempio a quello implementato su questo stesso sito designers.italia.it. 
```

2023-10-19 16:57 UTC, danielaiozzo commented on src/data/content/design-system/componenti/video-player.yaml
> +              ### Buone pratiche per i contenuti
```suggestion
              ### Buone pratiche sui contenuti
```

2023-10-19 16:57 UTC, danielaiozzo commented on src/data/content/design-system/componenti/video-player.yaml
> +              - È auspicabile l'inserimento di una immagine "thumbnail" che sostituisca il video in attesa del caricamento e/o consenso.
```suggestion
              - È preferibile inserire un'immagine "thumbnail" che sostituisce il video in attesa del caricamento e/o del consenso. 
```

2023-10-19 16:57 UTC, danielaiozzo commented on src/data/content/design-system/componenti/video-player.yaml
> +              - Devi fornire sottotitoli e trascrizioni come da normativa sull'accessibilità. Ti ricordiamo che i soli sottotitoli generati in automatico da una piattaforma non sono sufficienti, se n
```suggestion
              - Devi fornire sottotitoli e trascrizioni come da normativa sull'accessibilità. Ti ricordiamo che i soli sottotitoli generati in automatico da una piattaforma non sono sufficienti, perché è necessario che sia un umano a correggerli o integrarli. 
```

2023-10-19 16:57 UTC, danielaiozzo commented on src/data/content/design-system/componenti/video-player.yaml
> +              2. **overlay di consenso**: necesasrio in tutti i casi di streaming da piattaforme di terze parti, abilita l'implementazione di un meccanismo gestione cookie a norma GDPR;
```suggestion
              2. **overlay di consenso**: necessario in tutti i casi di streaming da piattaforme di terze parti, abilita la presenza di un meccanismo gestione cookie a norma GDPR;  
```

2023-10-19 16:57 UTC, danielaiozzo commented on src/data/content/design-system/componenti/video-player.yaml
> +              4. **sottotitoli**: necessari in tutti i casi ci sia parlato nel video;
```suggestion
              4. **sottotitoli**: necessari in tutti i casi ci sia del parlato nel video;
```

2023-10-19 16:57 UTC, danielaiozzo commented on src/data/content/design-system/componenti/video-player.yaml
> +              5. **trascrizione**: necessaria in tutti i casi ci sia parlato nel videoo necessità di descrizione di rumori e altro tipo di audio.
```suggestion
              5. **trascrizione**: necessaria in tutti i casi in cui è presente del parlato nel video, sia necessario descrivere rumori e altro tipo di audio.
```

2023-10-19 17:03 UTC, Fupete commented on src/data/content/design-system/componenti/video-player.yaml
> +              Il componente video player è utile per mostrare contenuti video nelle pagine del proprio sito. È possibile utilizzarlo per video caricati nel proprio hosting o per video incorporati da
```suggestion
              Il componente video player è utile per mostrare contenuti video nelle pagine del proprio sito. Si può usare per video caricati su un hosting proprio oppure per video provenienti da piattaforme di terze parti, utilizzando la variante con overlay di consenso per la privacy.   
```

2023-10-19 17:04 UTC, Fupete commented on src/data/content/design-system/componenti/video-player.yaml
> +              - Ti ricordiamo che i soli sottotitoli generati in automatico da una piattaforma non sono sufficienti, se non controllati ed eventualmente corretti o integrati da un umano.
```suggestion
              - Ti ricordiamo che i soli sottotitoli generati in automatico da una piattaforma non sono sufficienti, perché è necessario che sia un umano a correggerli o integrarli.
```

2023-10-19 17:07 UTC, danielaiozzo requested changes

2023-10-20 15:55 UTC, danielaiozzo requested changes
content additions

2023-10-20 15:55 UTC, danielaiozzo commented on src/data/content/design-system/componenti/video-player.yaml
> +              - Mostra video che rispondano a bisogni dell'utente, ad esempio semplificando l'accesso a informazioni o fornendo istruzioni su come svolgere attività.
```suggestion
              - Mostra video che rispondano a bisogni dell'utente, ad esempio semplificando l'accesso a informazioni o fornendo istruzioni su come svolgere attività.
              - Se il video è uno dei contenuti predominanti della pagina, abbi cura di associargli un titolo e/o una descrizione o testo breve per offrire agli utenti informazioni di contesto preliminari alla visione.
              - Il contenuto video non dovrebbe essere usato come unica modalità per veicolare informazioni salienti nell'ambito del sito o servizio.
```

2023-10-20 16:10 UTC, danielaiozzo approved these changes

2023-10-20 16:55 UTC, merged