content: media archive
italia/designers.italia.it pull request #1020
Opened 2023-10-19 13:09 UTC by Fupete

2023-10-23 11:03 UTC, Fupete commented
Reminder: remove links to youtube auto transcriptions if not an a11y days video.

2023-10-23 13:29 UTC, danielaiozzo commented on src/data/content/community/media/20210706-sviluppare-nuovi-servizi-pubblici-in-modalità-open-source.yaml
> +    title: 'Sviluppare nuovi servizi pubblici in modalità open sourc'
```suggestion
    title: 'Sviluppare nuovi servizi pubblici in modalità open source'
```

2023-10-23 13:56 UTC, danielaiozzo requested changes

2023-10-23 13:56 UTC, danielaiozzo commented on src/data/content/community/media/20210615-progettare-un-servizio-pubblico-digitale.yaml
> +            Webinar del 15/06/2021 del corso "Progettare, sviluppare ed erogare servizi pubblici digitali". Come realizzare un servizio digitale? In questo video, vengono affrontati il processo di pr
```suggestion
            Webinar del 15/06/2021 del corso "Progettare, sviluppare ed erogare servizi pubblici digitali". Come realizzare un servizio digitale? In questo video, vengono affrontati il processo di progettazione, di sviluppo e la messa in produzione con un focus sulla progettazione di un servizio digitale di qualità: per esempio, cosa vuol dire progettare per l'utente un servizio pubblico digitale, come fare ad avere un impatto positivo sul cittadino e sul sistema Paese, come impostare un processo di progettazione virtuoso (principi e competenze necessarie).
```

2023-10-23 13:56 UTC, danielaiozzo commented on src/data/content/community/media/20211109-progettare-il-sito-web-di-un-comune.yaml
> +          Webinar del 09/11/2021 del corso "Progettare e realizzare il sito web di un Comune". Il webinr intende fornire informazioni di contesto sulle Linee Guida di riferimento e sulla metodologia
```suggestion
          Webinar del 09/11/2021 del corso "Progettare e realizzare il sito web di un Comune". Il webinar intende fornire informazioni di contesto sulle Linee Guida di riferimento e sulla metodologia di progettazione proposta da Designers Italia. In particolare, quali sono le attività da svolgere e quali strumenti concreti Designers Italia mette a disposizione per le diverse figure coinvolte nei progetti di ideazione dei servizi pubblici digitali della PA: risorse, strumenti operativi e casi studio di buone pratiche.
```

2023-10-23 13:56 UTC, danielaiozzo commented on src/data/content/community/media/20211123-l-architettura-informativa-i-contenuti-e-l-interfaccia-utente-del-sito-web-di-un-comune.yaml
> +            Webinar del 23/11/2021 del corso "Progettare e realizzare il sito web di un Comune". Il Modello di sito web di un Comune propone template pronti per l'uso e un pacchetto di strumenti per
```suggestion
            Webinar del 23/11/2021 del corso "Progettare e realizzare il sito web di un Comune". Il Modello di sito web di un Comune propone template pronti per l'uso e un pacchetto di strumenti per aiutare a offrire un'esperienza d'uso efficace e inclusiva agli utenti. Dove sono e come si utilizzano le risorse e gli strumenti messi a disposizione: stato dell'arte e prospettive, con uno sguardo a dove trovare la community di riferimento.
```

2023-10-23 13:56 UTC, danielaiozzo commented on src/data/content/community/media/20211124-rilascio-e-riuso-di-un-software-open-source.yaml
> +  description: Le esperienze del Consiglio Nazioale delle Ricerche e dell’Istituto Superiore di Sanità.
```suggestion
  description: Le esperienze del Consiglio Nazionale delle Ricerche e dell’Istituto Superiore di Sanità. 
```

2023-10-23 13:56 UTC, danielaiozzo commented on src/data/content/community/media/20211124-rilascio-e-riuso-di-un-software-open-source.yaml
> +    subtitle: Le esperienze del Consiglio Nazioale delle Ricerche e dell’Istituto Superiore di Sanità
```suggestion
    subtitle: Le esperienze del Consiglio Nazionale delle Ricerche e dell’Istituto Superiore di Sanità
```

2023-10-23 13:56 UTC, danielaiozzo commented on src/data/content/community/media/20220209-l-importanza-di-un-design-system-per-i-servizi-pubblici-digitali.yaml
> +      tags: [Design system, Porgettazione interfaccia, Sviluppo interfaccia]
```suggestion
      tags: [Design system, Progettazione interfaccia, Sviluppo interfaccia]
```

2023-10-23 13:56 UTC, danielaiozzo commented on src/data/content/community/media/20220323-scopriamo-bootstrap-italia-2-0.yaml
> +            Community lab di Developers Italia e Designers Italia del 23/03/2022. Incontro dedicato a Bootstrap Italia 2.0, una delle risorse del design system del Paese, e alla sua utilità per svilu
```suggestion
            Community lab di Developers Italia e Designers Italia del 23/03/2022. Incontro dedicato a Bootstrap Italia 2.0, una delle risorse del design system del Paese e alla sua utilità per sviluppare le interfacce dei servizi pubblici digitali.
```

2023-10-24 07:42 UTC, danielaiozzo approved these changes

2023-10-25 15:58 UTC, Fupete commented
I will merge this tomorrow morning.

2023-10-26 08:49 UTC, merged