content: added shadows text and examples
italia/designers.italia.it pull request #1051
Opened 2023-11-07 09:26 UTC by zetareticoli

2023-11-07 11:23 UTC, Fupete commented on src/data/content/design-system/fondamenti/ombreggiature.yaml
> +  description: "La griglia di impaginazione rappresenta la struttura invisibile che permette di organizzare i contenuti della pagina"
```suggestion
  description: "Le ombre aggiungono profondità, contrasto e interesse visivo ai componenti, contribuendo a migliorare l'usabilità e l'aspetto generale dell'interfaccia"
```

2023-11-07 11:23 UTC, Fupete commented on src/data/content/design-system/fondamenti/ombreggiature.yaml
> +    subtitle: "Le ombre aggiungono profondità, contrasto e interesse visivo ai componenti, contribuendo a migliorare l'usabilità e l'aspetto generale dell'interfaccia."
```suggestion
    subtitle: "Le ombre aggiungono profondità, contrasto e interesse visivo ai componenti, contribuendo a migliorare l'usabilità e l'aspetto generale dell'interfaccia"
```

2023-11-07 11:28 UTC, Fupete commented on src/data/content/design-system/fondamenti/ombreggiature.yaml
> +  name: Ombreggiature
@zetareticoli non sono sicuro del nome. Secondo me sono "Ombre". "Ombreggiatura" di solito si riferisce allo shading delle superfici forse? Qui parliamo di vere e proprie ombre dell'oggetto che possiete questa priprietà no? 🤔 cc @danielaiozzo

2023-11-07 11:28 UTC, Fupete commented on src/data/content/design-system/fondamenti/ombreggiature.yaml
> +            - **migliroare leggibilità**, le ombre separano gli elementi dallo sfondo, migliorando leggibilità del testo e la comprensione delle informazioni;
```suggestion
            - **migliorare leggibilità**: le ombre separano gli elementi dallo sfondo, migliorando leggibilità del testo e la comprensione delle informazioni;
```

2023-11-07 11:29 UTC, Fupete commented on src/data/content/design-system/fondamenti/ombreggiature.yaml
> +            - **creare gerarchia**, le ombre sono utilizzate per distinguere gli elementi principali da quelli secondari, guidando l'utente attraverso l'interfaccia e mettendo in evidenza elementi im
```suggestion
            - **creare gerarchia**: le ombre sono utilizzate per distinguere gli elementi principali da quelli secondari, guidando l'utente attraverso l'interfaccia e mettendo in evidenza elementi importanti;
```

2023-11-07 11:29 UTC, Fupete commented on src/data/content/design-system/fondamenti/ombreggiature.yaml
> +            - **aggiungere realismo**, le ombre creano un senso di profondità e realismo all'interno dell'interfaccia, rendendo più attraenti gli elementi primari.
```suggestion
            - **aggiungere realismo**: le ombre creano un senso di profondità e realismo all'interno dell'interfaccia, rendendo più attraenti gli elementi primari.
```

2023-11-07 11:29 UTC, Fupete commented on src/data/content/design-system/fondamenti/ombreggiature.yaml
> +            - **altezza e diffusione**, utilizza ombre con un'altezza e una diffusione adeguate in base alle dimensioni e all'importanza dell'elemento. Elementi più grandi o più rilevanti possono ric
```suggestion
            - **altezza e diffusione**: utilizza ombre con un'altezza e una diffusione adeguate in base alle dimensioni e all'importanza dell'elemento. Elementi più grandi o più rilevanti possono richiedere ombre più pronunciate;
```

2023-11-07 11:29 UTC, Fupete commented on src/data/content/design-system/fondamenti/ombreggiature.yaml
> +            - **direzione**, mantieni una direzione coerente per le ombre all'interno dell'interfaccia, per evitare incoerenze visive. Ad esempio, le ombre potrebbero essere posizionate generalmente
```suggestion
            - **direzione**: mantieni una direzione coerente per le ombre all'interno dell'interfaccia, per evitare incoerenze visive. Ad esempio, le ombre potrebbero essere posizionate generalmente in basso a destra per creare un aspetto uniforme.;
```

2023-11-07 11:29 UTC, Fupete commented on src/data/content/design-system/fondamenti/ombreggiature.yaml
> +            - **evita un uso eccessivo**, applica le ombre con parsimonia per evitare un aspetto confusionario o caotico.
```suggestion
            - **evita un uso eccessivo**: applica le ombre con parsimonia per evitare un aspetto confusionario o caotico.
```

2023-11-08 10:10 UTC, zetareticoli commented on src/data/content/design-system/fondamenti/ombreggiature.yaml
> +  name: Ombreggiature
Su BS Italia le chiamiamo Ombreggiature, anche il file JSON che usiamo come metadata `bsi/organizzare-gli-spazi/ombreggiature`

2023-11-08 16:52 UTC, Fupete commented on src/data/content/design-system/fondamenti/ombreggiature.yaml
> +      noSpace: true
```suggestion
      noSpace: true
      paddingLeft: true
```

2023-11-08 17:26 UTC, Fupete requested changes
@zetareticoli è saltato il kangaroo nell'hero... 
![immagine](https://github.com/italia/designers.italia.it/assets/6736103/b0754f7c-7d31-4fb1-bbef-343e1700cc79)

Non capisco perché su due piedi non trovo l'errore 🤔. 
Il resto dei contenuti per me vanno bene.

2023-11-08 18:31 UTC, zetareticoli commented on src/data/content/design-system/fondamenti/ombreggiature.yaml
> +  name: Ombreggiature
Visto che "Spaziatura" è al singolare, possiamo mettere "Ombreggiatura" per uniformare? /cc @danielaiozzo

2023-11-08 18:33 UTC, zetareticoli commented
> @zetareticoli è saltato il kangaroo nell'hero... ![immagine](https://user-images.githubusercontent.com/6736103/281490461-b0754f7c-7d31-4fb1-bbef-343e1700cc79.png)
> 
> Non capisco perché su due piedi non trovo l'errore 🤔. Il resto dei contenuti per me vanno bene.

fixed

2023-11-09 08:33 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/ombreggiature.yaml
> +  name: Ombreggiature
@zetareticoli ti ho lasciato un commento simile a quello di @Fupete anche su "spaziatura", personalmente preferisco le versioni + short ma se ci sono limiti rispetto ai metadata ne riparliamo

2023-11-09 17:40 UTC, zetareticoli commented
Resta da decidere se usare "Ombre", "Ombreggiature" o "Ombreggiatura".

In caso, dobbiamo uniformare anche BS Italia. 

/cc @Fupete @danielaiozzo

2023-11-10 09:08 UTC, zetareticoli commented
Ci viene in soccorso questa definizione:

L'ombreggiatura (in inglese shading), in [computer grafica](https://it.wikipedia.org/wiki/Computer_grafica), è il modo in cui la luce interagisce con la [mesh poligonale](https://it.wikipedia.org/wiki/Mesh_poligonale), in base all'assorbimento o la riflessione della luce, l'angolo di incidenza e l'angolo di visione[[1]](https://it.wikipedia.org/wiki/Ombreggiatura#cite_note-1), e altre caratteristiche.

Può avere senso allora parlare di "Ombre", correggendo lo stesso termine su BS Italia.

2023-11-10 11:03 UTC, danielaiozzo requested changes

2023-11-10 11:03 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/ombreggiature.yaml
> +            - **aggiungere realismo**: le ombre creano un senso di profondità e realismo all'interno dell'interfaccia, rendendo più attraenti gli elementi primari.
```suggestion
            - **aggiungere realismo**: le ombre creano un'impressione di profondità e realismo, mettendo in risalto visivo gli elementi primari dell'interfaccia.
```

2023-11-10 11:03 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/ombreggiature.yaml
> +            Per garantire coerenza e uniformità, segui alcune buone prassi nell'uso delle ombreggiature:
```suggestion
            Per garantire coerenza e uniformità, segui alcune buone prassi nell'uso delle ombre:
```

2023-11-10 11:03 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/ombreggiature.yaml
> +            - **altezza e diffusione**: utilizza ombre con un'altezza e una diffusione adeguate in base alle dimensioni e all'importanza dell'elemento. Elementi più grandi o più rilevanti possono ric
```suggestion
            - **altezza e diffusione**: usa ombre con un'altezza e una diffusione adeguate in base alle dimensioni e all'importanza dell'elemento. Elementi più grandi o più rilevanti possono richiedere ombre più pronunciate;
```

2023-11-10 11:03 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/ombreggiature.yaml
> +            - **direzione**: mantieni una direzione coerente per le ombre all'interno dell'interfaccia, per evitare incoerenze visive. Ad esempio, le ombre potrebbero essere posizionate generalmente
```suggestion
            - **direzione**: mantieni una direzione coerente per le ombre all'interno dell'interfaccia, per evitare incoerenze visive. Ad esempio, le ombre potrebbero essere posizionate generalmente in basso a destra per creare un aspetto uniforme;
```

2023-11-10 15:37 UTC, danielaiozzo submitted a review, later dismissed
dopo questo minor fix è ok per me

2023-11-10 15:37 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/ombre.yaml
> +            - **migliorare leggibilità**: le ombre separano gli elementi dallo sfondo, migliorando leggibilità del testo e la comprensione delle informazioni;
```suggestion
            - **migliorare la leggibilità**: le ombre separano gli elementi dallo sfondo, migliorando la leggibilità del testo e la comprensione delle informazioni;
```

2023-11-10 16:07 UTC, Fupete approved these changes

2023-11-10 17:14 UTC, merged