content: added spacing foundation
italia/designers.italia.it pull request #1058
Opened 2023-11-08 18:06 UTC by zetareticoli

Spacing foundation page includes some info about what they are and how to use them.

Plus, I've added the token tables. I think we should add design tokens for all foundations pages (color, shadows, borders, etc).

2023-11-08 21:32 UTC, danielaiozzo requested changes

2023-11-08 21:32 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/spaziatura.yaml
> +  description: "La spaziatura svolge un ruolo fondamentale nella creazione di un layout ben strutturato e nella definizione del respiro e dell'equilibrio. Un utilizzo coerente degli spazi contribuisc
```suggestion
  description: "La spaziatura ha il ruolo fondamentale di creare un layout dalla struttura armonica e di definire gli intervalli spaziali fra gli elementi della pagina. Un uso coerente ed equilibrato degli spazi contribuisce a migliorare la leggibilità, l'usabilità e l'aspetto generale di un'interfaccia."
```

2023-11-08 21:32 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/spaziatura.yaml
> +    subtitle: "Le spaziatura svolge un ruolo fondamentale nella creazione di un layout ben strutturato e nella definizione del respiro e dell'equilibrio. Un utilizzo coerente degli spazi contribuisce
```suggestion
    subtitle: "La spaziatura ha il ruolo fondamentale di creare un layout dalla struttura armonica e di definire gli intervalli spaziali fra gli elementi della pagina. Un uso coerente ed equilibrato degli spazi contribuisce a migliorare la leggibilità, l'usabilità e l'aspetto generale di un'interfaccia."
```

2023-11-08 21:32 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/spaziatura.yaml
> +            2. **creare respiro**: gli spazi forniscono respiro visuale tra gli elementi, evitando sovrapposizioni indesiderate e migliorando la comprensione delle informazioni.
```suggestion
            2. **creare respiro**: gli spazi forniscono respiro visuale tra gli elementi, evitando sovrapposizioni indesiderate e migliorando la comprensione delle informazioni;
```

2023-11-08 21:32 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/spaziatura.yaml
> +            3. **fornire coerenza**: l'uso consistente degli spazi contribuisce a garantire che i layouts siano uniformi e armoniosi in tutte le interfacce.
```suggestion
            3. **fornire coerenza**: l'uso consistente degli spazi contribuisce a garantire che i layout siano uniformi e armoniosi in tutte le interfacce.
```

2023-11-08 21:32 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/spaziatura.yaml
> +            - **definisci una gerarchia** che consenta di gestire le distanze tra gli elementi in modo logico, utilizando spazi più ampi tra le sezioni di una pagina e spazi più stretti all'interno d
```suggestion
            - **definisci una gerarchia** per gestire le distanze tra gli elementi in modo logico, utilizzando spazi più ampi tra le sezioni di una pagina e spazi più stretti all'interno di una stessa sezione o componente;
```

2023-11-08 21:32 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/spaziatura.yaml
> +            - **utilizza i design token** dedicati agli spazi, rispettando la distinzione tra quelli per lo spazio verticale (`spacing-stack`), quelli per lo spazio orizzontale (`spacing-inline`) e i
```suggestion
            - **usa i design token** dedicati agli spazi, rispettando la distinzione tra quelli per lo spazio verticale (`spacing-stack`), quelli per lo spazio orizzontale (`spacing-inline`) e infine quelli per lo spazio interno ad un elemento (`spacing-inset`);
```

2023-11-08 21:32 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/spaziatura.yaml
> +            - **spaziatura interna** (_inset_) ad una sezione o componente.
```suggestion
            - **spaziatura interna** (_inset_) a una sezione o componente.
```

2023-11-09 08:27 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/spaziatura.yaml
> +  name: Spaziatura
@zetareticoli spazio, spaziatura o spaziature?

2023-11-09 11:40 UTC, zetareticoli commented on src/data/content/design-system/fondamenti/spaziatura.yaml
> +  name: Spaziatura
La traduzione letterale di `spacing` è "spaziatura".

Possiamo secondo me anche usare "spazio" o "spazi" quando ci riferiamo ad esempi pratici. 

/cc @Fupete

2023-11-10 11:06 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/spaziatura.yaml
> +  name: Spaziatura
ne ho parlato stamane con @Fupete propendiamo per "spaziature"

2023-11-10 11:11 UTC, danielaiozzo requested changes

2023-11-10 11:11 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/spaziatura.yaml
> +  description: "La spaziatura ha il ruolo fondamentale di creare un layout dalla struttura armonica e di definire gli intervalli spaziali fra gli elementi della pagina. Un uso coerente ed equilibrato
```suggestion
  description: "Le spaziature hanno il ruolo fondamentale di creare un layout dalla struttura armonica e di definire gli intervalli di spazio fra gli elementi della pagina. Un uso coerente ed equilibrato delle spaziature contribuisce a migliorare la leggibilità, l'usabilità e l'aspetto generale di un'interfaccia."
```

2023-11-10 11:11 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/spaziatura.yaml
> +  name: Spaziatura
```suggestion
  name: Spaziature
```

2023-11-10 11:11 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/spaziatura.yaml
> +  pathname: /design-system/fondamenti/spaziatura/
```suggestion
  pathname: /design-system/fondamenti/spaziature/
```

2023-11-10 11:11 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/spaziatura.yaml
> +    title: Spaziatura
```suggestion
    title: Spaziature
```

2023-11-10 11:11 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/spaziatura.yaml
> +    subtitle: "La spaziatura ha il ruolo fondamentale di creare un layout dalla struttura armonica e di definire gli intervalli spaziali fra gli elementi della pagina. Un uso coerente ed equilibrato
```suggestion
    subtitle: "Le spaziature hanno il ruolo fondamentale di creare un layout dalla struttura armonica e di definire gli intervalli di spazio fra gli elementi della pagina. Un uso coerente ed equilibrato delle spaziature contribuisce a migliorare la leggibilità, l'usabilità e l'aspetto generale di un'interfaccia."
```

2023-11-10 11:11 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/spaziatura.yaml
> +            Gli spazi servono a:
```suggestion
            Le spaziature servono a:
```

2023-11-10 11:11 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/spaziatura.yaml
> +            1. **organizzare un layout**: gli spazi definiscono la disposizione degli elementi all'interno delle pagine e dei componenti, garantendo il rispetto di una struttura chiara e coesa;
```suggestion
            1. **organizzare un layout**: definiscono la disposizione degli elementi all'interno delle pagine e dei componenti, garantendo il rispetto di una struttura chiara e coesa;
```

2023-11-10 11:11 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/spaziatura.yaml
> +            2. **creare respiro**: gli spazi forniscono respiro visuale tra gli elementi, evitando sovrapposizioni indesiderate e migliorando la comprensione delle informazioni;
```suggestion
            2. **creare respiro**: forniscono "respiro visuale" tra gli elementi, evitando sovrapposizioni indesiderate e migliorando la comprensione delle informazioni;
```

2023-11-10 11:11 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/spaziatura.yaml
> +            3. **fornire coerenza**: l'uso consistente degli spazi contribuisce a garantire che i layout siano uniformi e armoniosi in tutte le interfacce.
```suggestion
            3. **fornire coerenza**: l'uso consistente delle spaziature contribuisce a garantire che i layout siano uniformi e armoniosi in tutte le interfacce.
```

2023-11-10 11:11 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/spaziatura.yaml
> +            - **usa i design token** dedicati agli spazi, rispettando la distinzione tra quelli per lo spazio verticale (`spacing-stack`), quelli per lo spazio orizzontale (`spacing-inline`) e infine
```suggestion
            - **usa i design token** dedicati alle spaziature, rispettando la distinzione tra quelli per lo spazio verticale (`spacing-stack`), quelli per lo spazio orizzontale (`spacing-inline`) e infine quelli per lo spazio interno ad un elemento (`spacing-inset`);
```

2023-11-10 14:04 UTC, Fupete approved these changes

2023-11-10 14:08 UTC, danielaiozzo submitted a review, later dismissed
dopo questo mini fix per me è ok

2023-11-10 14:08 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/spaziature.yaml
> +            2. **creare respiro**: forniscono "respiro visuale" tra gli elementi, evitando sovrapposizioni indesiderate e migliorando la comprensione delle informazioni;
```suggestion
            2. **creare respiro**: forniscono "respiro visuale" agli elementi, evitando sovrapposizioni indesiderate e migliorando la comprensione delle informazioni;
```

2023-11-10 16:26 UTC, merged