content: update piano attivita Q4 2023
italia/designers.italia.it pull request #1076
Opened 2023-11-14 10:54 UTC by Fupete

2023-11-14 11:11 UTC, danielaiozzo requested changes

2023-11-14 11:11 UTC, danielaiozzo commented on src/data/content/community/piano-attivita.yaml
> +            Avvio delle attività di ricerca utente finalizzate alla realizzazione del modello di sito per le Aziende Sanitarie Locali.
```suggestion
            Avvio delle attività di ricerca utente dedicate alla realizzazione del modello di sito per le Aziende Sanitarie Locali.
```

2023-11-14 11:11 UTC, danielaiozzo commented on src/data/content/community/piano-attivita.yaml
> +            Avvio delle attività di ricerca utente finalizzate alla realizzazione del modello di sito per i musei pubblici.
```suggestion
            Avvio delle attività di ricerca utente dedicate alla realizzazione del modello di sito per i musei pubblici.
```

2023-11-14 14:24 UTC, danielaiozzo commented on src/data/content/community/piano-attivita.yaml
> +          title: "Esperienza del cittadino nei servizi pubblici: dalla Misura alla pratica" #C
```suggestion
          title: "Esperienza del cittadino nei servizi pubblici: dalla misura alla pratica" #C
```

2023-11-14 14:25 UTC, danielaiozzo commented on src/data/content/community/piano-attivita.yaml
> +          title: "Esperienza del cittadino nei servizi pubblici: dalla Misura alla pratica" #C
c'è qualche ragione per cui "Misura" deve essere maiuscolo qui?

2023-11-14 14:29 UTC, danielaiozzo requested changes

2023-11-14 14:29 UTC, danielaiozzo commented on src/data/content/community/piano-attivita.yaml
> +            Al via un ciclo di webinar per scoprire come utilizzare al meglio tutte le risorse dedicate ai Comuni, in collaborazione con l'Associazione Nazionale Comuni Italiani (ANCI).
```suggestion
            Al via un ciclo di webinar per scoprire come usare al meglio tutte le risorse dedicate ai Comuni, in collaborazione con l'Associazione Nazionale Comuni Italiani (ANCI).
```

2023-11-14 14:29 UTC, danielaiozzo commented on src/data/content/community/piano-attivita.yaml
> +            Continuo lavori di consolidamento del nuovo sito Designers Italia, in particolare avvio seconda sessione di test di usabilità, integrazioni funzionalità per l'archivio media e altre lavor
```suggestion
            Prosecuzione dei lavori di consolidamento del nuovo sito Designers Italia, in particolare avvio seconda sessione di test di usabilità, integrazione di funzionalità per l'archivio media e altre lavorazioni per ottimizzare l'esperienza utente, la manutenibilità e la scalabilità nel tempo.
```

2023-11-14 15:50 UTC, Fupete commented on src/data/content/community/piano-attivita.yaml
> +          title: "Esperienza del cittadino nei servizi pubblici: dalla Misura alla pratica" #C
cc @danielenole

2023-11-15 08:10 UTC, Fupete commented on src/data/content/community/piano-attivita.yaml
> +          title: "Esperienza del cittadino nei servizi pubblici: dalla Misura alla pratica" #C
È il titolo del corso @danielaiozzo.

2023-11-15 09:29 UTC, danielaiozzo approved these changes

2023-11-15 09:35 UTC, bfabio commented on src/data/content/community/piano-attivita.yaml
> +          title: "Esperienza del cittadino nei servizi pubblici: dalla Misura alla pratica" #C
Dato che è il nome del webinar e non lo si può cambiare (e sarebbe da cambiare, perché usa cittadino - al maschile e pure implica che solo l'esperienza dei cittadini sia il caso di studio dei Comuni. I non cittadini, ehi, tornate la prossima volta :shrug:), che dite di una cosa tipo

```
title: "Webinar/Corso: “blah blah titolo del corso verbatim”"
```

2023-11-15 09:36 UTC, bfabio approved these changes

2023-11-15 09:41 UTC, merged