docs: sizing foundation
italia/designers.italia.it pull request #1107
Opened 2023-11-29 17:26 UTC by zetareticoli

Created the 'Dimensioni' (Sizing) foundation page.

2023-12-01 12:45 UTC, danielaiozzo requested changes

2023-12-01 12:45 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/dimensioni.yaml
> +            Le dimensioni di un elemento sono misure che **definiscono lo spazio occupato** in altezza e in larghezza da un elemento.
@zetareticoli forse qui - e in base a ciò che intuisco anche da quanto scritto sotto a proposito delle griglie etc - forse potremmo parlare anche di "proporzioni" e di "disposizione nel resto dello spazio", ma dimmi tu

2023-12-01 12:45 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/dimensioni.yaml
> +            Le misure sono espresse in **percentuale** perché possono essere relative a:
```suggestion
            Le misure delle dimensioni sono espresse in **percentuale** e possono essere relative a: 
```

2023-12-01 12:45 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/dimensioni.yaml
> +            Le misure sono espresse in **percentuale** perché possono essere relative a:
@zetareticoli 
1. qui non so se è più corretto parlare di "misure" o "proprietà" delle dimensioni
2. il fatto che siano in percentuale deriva dal fatto che sono relative a? (il senso del "perché" che ho tolto insomma, e che ho sostituito, se sei d'accordo, con "e")

2023-12-01 12:45 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/dimensioni.yaml
> +            - la dimensione del contenitore in cui è inserito l'elemento, come le colonne della griglia.
```suggestion
            - la dimensione del contenitore in cui è inserito l'elemento, ad esempio le colonne della griglia. 
```

2023-12-01 12:45 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/dimensioni.yaml
> +            È possibile utilizzare misure diverse per uno stesso elemento in base a specifiche necessità di layout.
```suggestion
            È possibile utilizzare misure diverse per uno stesso elemento in base a specifiche necessità di layout e per garantire che gli elementi di design siano sempre ottimizzati in base a risoluzione e tipo di dispositivo. 
```

2023-12-01 12:45 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/dimensioni.yaml
> +            È possibile utilizzare misure diverse per uno stesso elemento in base a specifiche necessità di layout.
@zetareticoli FYCheck

2023-12-01 12:45 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/dimensioni.yaml
> +            Ad esempio, un pulsante può avere una dimensione `100%` su dispositivi mobile perché essere facilmente cliccabile, mentre una dimensione ridotta su dispositivi più grandi dove lo spazio a
```suggestion
            Ad esempio, un pulsante può avere una dimensione `100%` su dispositivi mobili per facilitare l'interazione in uno spazio ridotto, mentre una dimensione inferiore su dispositivi più grandi dove invece lo spazio a disposizione per interagire con gli elementi dello schermo è maggiore.
```

2023-12-01 12:45 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/dimensioni.yaml
> +            Queste misure si **adattano alla griglia**, ma non la sostituiscono in quanto non prevedono intercolonna e margini laterali.
```suggestion
            Queste misure si **adattano alla griglia** ma non la sostituiscono, in quanto non prevedono intercolonna e margini laterali.
```

2023-12-01 12:45 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/dimensioni.yaml
> +  description: "Le misure utilizzate per definire lo spazio occupato dagli elementi all'interno di un'interfaccia"
```suggestion
  description: "Le misure che definiscono lo spazio occupato dagli elementi di design all'interno di un'interfaccia"
```

2023-12-01 12:45 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/dimensioni.yaml
> +    subtitle: "Le misure utilizzate per definire lo spazio occupato dagli elementi all'interno di un'interfaccia"
```suggestion
    subtitle: "Le misure che definiscono lo spazio occupato dagli elementi di design all'interno di un'interfaccia"
```

2023-12-01 16:26 UTC, zetareticoli commented on src/data/content/design-system/fondamenti/dimensioni.yaml
> +            Le dimensioni di un elemento sono misure che **definiscono lo spazio occupato** in altezza e in larghezza da un elemento.
mi sembra corretto 👍

2023-12-04 16:12 UTC, danielaiozzo requested changes
ok for me with a minor fix

2023-12-04 16:12 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/dimensioni.yaml
> +            L'uso di dimensioni standard garantisce coerenza visiva e armonia, migliorando non solo l'aspetto estetico dell'interfaccia ma anche la sua usabilità complessiva.
```suggestion
            L'uso di dimensioni standard garantisce coerenza visiva e armonia, migliorando non solo l'aspetto estetico dell'interfaccia ma anche la sua usabilità generale. 
```

2023-12-05 10:08 UTC, zetareticoli commented
@Fupete waiting for your final review

2023-12-05 16:01 UTC, danielaiozzo approved these changes

2023-12-14 16:19 UTC, Fupete approved these changes
Ho corretto il pathname e aggiunto la card nella pagina fondamenti. Ne ho approfittato per farae refactor anche di quello `yaml`.

2023-12-14 16:39 UTC, merged