docs: Tabs component page
italia/designers.italia.it pull request #1120
Opened 2023-12-07 16:38 UTC by zetareticoli

Added the first content draft for the tabs component.

## Status 

- [x] usage
- [ ] design specs
- [x] component status
- [ ] a11y

2023-12-14 21:52 UTC, Fupete commented on src/data/content/design-system/componenti/tabs.yaml
> +metadata:
Post-it(for me): we need also the "tab" redirect here

2023-12-15 10:05 UTC, danielaiozzo requested changes

2023-12-15 10:05 UTC, danielaiozzo commented on src/data/content/design-system/componenti/tabs.yaml
> +              - Fai in modo che le tabs siano chiaramente **distinguibili**, utilizzando colori o stili contrastanti;
```suggestion
              - fai in modo che le tabs siano chiaramente **distinguibili**, utilizzando colori o stili contrastanti;
```

2023-12-15 10:05 UTC, danielaiozzo commented on src/data/content/design-system/componenti/tabs.yaml
> +              - Indica chiaramente quale tab è **attivo**, attraverso elementi visivi come colore o bordo.
```suggestion
              - indica chiaramente quale tab è **attivo**, attraverso elementi visivi come colore o bordo.
```

2023-12-15 10:05 UTC, danielaiozzo commented on src/data/content/design-system/componenti/tabs.yaml
> +              - **default**: un tab si presenta nello stato normale quando è attivo ma l'utente non ci interagisce;
```suggestion
              - **default**: una tab si presenta nello stato normale quando è attivo ma l'utente non ci interagisce;
```

2023-12-15 10:05 UTC, danielaiozzo commented on src/data/content/design-system/componenti/tabs.yaml
> +              - **disabled**: indica che il tab è disattivato e non è possibile interagire con esso.
```suggestion
              - **disabled**: indica che la tab è disattivata e non è possibile interagire con essa.
```

2023-12-15 10:05 UTC, danielaiozzo commented on src/data/content/design-system/componenti/tabs.yaml
> +              - **active**: si manifesta quando un tab è selezionato, ovvero è stato cliccato dall'utente;
```suggestion
              - **active**: si manifesta quando una tab è selezionata, ovvero è stata cliccata dall'utente;
```

2023-12-15 10:05 UTC, danielaiozzo commented on src/data/content/design-system/componenti/tabs.yaml
> +              - **hover**: si manifesta al passaggio del puntatore sul tab, è disponibile solo su dispositivi no-touch;
```suggestion
              - **hover**: si manifesta al passaggio del puntatore sulla tab, è disponibile solo su dispositivi no-touch;
```

2023-12-15 10:05 UTC, danielaiozzo commented on src/data/content/design-system/componenti/tabs.yaml
> +              La variante tabs orizzontale è composto da:
```suggestion
              La variante tab orizzontale è composta da:
```

2023-12-15 10:05 UTC, danielaiozzo commented on src/data/content/design-system/componenti/tabs.yaml
> +              La variante tabs verticale è composto da:
```suggestion
              La variante tab verticale è composta da:
```

2023-12-15 10:05 UTC, danielaiozzo commented on src/data/content/design-system/componenti/tabs.yaml
> +              4. **sfondo**: il tab selezionato può avere uno sfondo (_opzionale_);
```suggestion
              4. **sfondo**: la tab selezionata può avere uno sfondo (_opzionale_); 
```

2023-12-15 10:05 UTC, danielaiozzo commented on src/data/content/design-system/componenti/tabs.yaml
> +              La variante tabs con card è composto da:
```suggestion
              La variante tab con card è composta da:
```

2023-12-15 10:05 UTC, danielaiozzo commented on src/data/content/design-system/componenti/tabs.yaml
> +              1. **bordo**: visibile su tre lati, è presente solo per il tab attivo;
```suggestion
              1. **bordo**: visibile su tre lati, è presente solo per la tab attiva;
```

2023-12-15 10:05 UTC, danielaiozzo commented on src/data/content/design-system/componenti/tabs.yaml
> +              - **default**: un tab si presenta nello stato normale quando è attivo ma l'utente non ci interagisce;
```suggestion
              - **default**: una tab si presenta nello stato normale quando è attivo ma l'utente non ci interagisce;
```

2023-12-15 10:05 UTC, danielaiozzo commented on src/data/content/design-system/componenti/tabs.yaml
> +              ### Tabs orizzontali
```suggestion
              ### Tab orizzontali
```

2023-12-15 10:05 UTC, danielaiozzo commented on src/data/content/design-system/componenti/tabs.yaml
> +              ### Tabs verticali
```suggestion
              ### Tab verticali
```

2023-12-15 10:05 UTC, danielaiozzo commented on src/data/content/design-system/componenti/tabs.yaml
> +              ![Anatomia dei tabs vertical](/images/design-system/componenti/tabs-vertical-anatomy.png)
```suggestion
              ![Anatomia delle tab verticali](/images/design-system/componenti/tabs-vertical-anatomy.png)
```

2023-12-15 10:05 UTC, danielaiozzo commented on src/data/content/design-system/componenti/tabs.yaml
> +              ### Tabs con card
```suggestion
              ### Tab con card
```

2023-12-15 10:05 UTC, danielaiozzo commented on src/data/content/design-system/componenti/tabs.yaml
> +              ![Anatomia dei tabs card](/images/design-system/componenti/tabs-card-anatomy.png)
```suggestion
              ![Anatomia delle tab card](/images/design-system/componenti/tabs-card-anatomy.png)
```

2023-12-15 10:06 UTC, danielaiozzo commented on src/data/content/design-system/componenti/tabs.yaml
> +              Le tabs servono a raggruppare contenuti diversi ma correlati, consentendo agli utenti di navigare tra le visualizzazioni senza uscire dalla pagina. Possono essere utilizzate su layout a
@zetareticoli per scelta stilistica su designers evitiamo i plurali delle parole inglesi quando il resto del testo è in ITA. manterrei perciò il nome del componente al plurale in titolo e voce di menu ma l'ho messo sempre al singolare nel testo. Ho inoltre uniformato al femminile, poiché nella prima parte del testo lo era, per poi passare nelle specifiche di design al maschile

2023-12-15 15:33 UTC, Fupete commented
@danielaiozzo @zetareticoli ho conteinuato a fare un po' di fix sulla scia di quelli iniziati da Daniela. 

Unica cosa che non mi torna: non dovremmo seguire l'approccio dei componenti già pronti per i due blocchi "Quando usarlo "Come usarlo"? Vedi Accordion, Buttons, ... dividendo tra "per" "attenzione a" "buone pratiche sui contenuti"? 

![immagine](https://github.com/italia/designers.italia.it/assets/6736103/dcc7bab8-4018-471d-bff8-de6c49ee0ac5)
Nell'immagine ad esempio a sinistra Tabs a destra Accordion.

2023-12-15 16:01 UTC, zetareticoli commented
Si, sono d'accordo. Ho cambiato l'ordine?

2023-12-15 16:55 UTC, danielaiozzo commented on src/data/content/design-system/componenti/tabs.yaml
> +              - Indica chiaramente quale tab è **attiva**, attraverso elementi visivi come colore o bordo.
```suggestion
              - Indica chiaramente quale tab è **attiva**, attraverso elementi visivi come colore o bordo.
              
              ### Buone pratiche sui contenuti
              
              - Scegli **etichette di testo brevi** come intestazioni delle tab (una o due parole).
              - Assicurati che le etichette comunichino in maniera **chiara e specifica** ciò che gli utenti vedranno attivando la tab
              
            
```

2023-12-18 10:27 UTC, zetareticoli commented
@danielaiozzo non ho visto la sezione "Attenzione a:" come richiesto da @Fupete - dobbiamo aggiungerla?

2023-12-18 11:24 UTC, danielaiozzo commented
> @danielaiozzo non ho visto la sezione "Attenzione a:" come richiesto da @Fupete - dobbiamo aggiungerla?

valuta tu se è necessaria, eviterei di generare ripetizioni, ma se invece si può trasformare qualcuna delle buone pratiche in "attenzione a" facciamolo per consistenza rispetto alla struttura degli altri componenti

2023-12-18 13:50 UTC, zetareticoli commented
> > @danielaiozzo non ho visto la sezione "Attenzione a:" come richiesto da @Fupete - dobbiamo aggiungerla?
> 
> valuta tu se è necessaria, eviterei di generare ripetizioni, ma se invece si può trasformare qualcuna delle buone pratiche in "attenzione a" facciamolo per consistenza rispetto alla struttura degli altri componenti

secondo me può restare così

2023-12-18 15:34 UTC, Fupete approved these changes

2023-12-18 15:35 UTC, Fupete commented
@zetareticoli @danielaiozzo ho uniformato per coerenza la struttura dei contenuti con gli altri componenti già revisionati. Scegliere una struttura differente possiamo farlo — per migliorare ancora — ma solo come ulteriore giro di review su tutti i componenti una volta raggiunta la beta, allo stato dell'arte dobbiamo privilegiare la coerenza.

2023-12-18 15:46 UTC, zetareticoli commented
> @zetareticoli @danielaiozzo ho uniformato per coerenza la struttura dei contenuti con gli altri componenti già revisionati. Scegliere una struttura differente possiamo farlo — per migliorare ancora — ma solo come ulteriore giro di review su tutti i componenti una volta raggiunta la beta, allo stato dell'arte dobbiamo privilegiare la coerenza.

ok, va bene, li penserò così già dal prossimo

2023-12-18 16:00 UTC, merged