docs: 'Proporzioni' foundation
italia/designers.italia.it pull request #1159
Opened 2023-12-27 17:19 UTC by zetareticoli

This page describes media aspect ratio foundation.

2024-01-10 09:56 UTC, zetareticoli commented
@Fupete e @danielaiozzo waiting for your review 😄

2024-01-10 10:13 UTC, danielaiozzo requested changes

2024-01-10 10:13 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/proporzioni.yaml
> +    subtitle: "Le proporzioni delle immagini indicano il rapporto tra larghezza e altezza. Quando si ridimensiona un'immagine, è essenziale mantenere questo rapporto per prevenire distorsioni."
```suggestion
    subtitle: "Le proporzioni delle immagini indicano il rapporto tra larghezza e altezza. Quando ridimensioni un'immagine, è essenziale mantenere questo rapporto per prevenire distorsioni."
```

2024-01-10 10:13 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/proporzioni.yaml
> +            Le proporzioni delle immagini per il web indicano il rapporto tra larghezza e altezza di un'immagine.
```suggestion
            Le proporzioni delle immagini per il web indicano il rapporto tra le misure di larghezza e altezza di queste. 
```

2024-01-10 10:13 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/proporzioni.yaml
> +            Il **mantenimento delle proporzioni** corrette è vitale non solo per evitare distorsioni visive, ma anche per garantire una visualizzazione ottimale su vari dispositivi. Un'immagine con p
```suggestion
            **Mantenere le proporzioni corrette** è cruciale non solo per evitare distorsioni visive, ma anche per garantire una visualizzazione ottimale sui vari dispositivi. Un'immagine con proporzioni errate potrebbe apparire corretta su un computer, ma potrebbe essere tagliata o distorta su uno smartphone o un tablet.
```

2024-01-10 10:13 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/proporzioni.yaml
> +            - mantenere l'**equilibrio** e l'armonia visiva durante il ridimensionamento dell'immagine;
```suggestion
            - mantenere l'**equilibrio** e l'armonia visiva se serve ridimensionare l'immagine;
```

2024-01-10 10:13 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/proporzioni.yaml
> +            - evitare **distorsioni** dell'immagine;
```suggestion
            - evitare **distorsioni**;
```

2024-01-10 10:13 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/proporzioni.yaml
> +            Per utilizzare correttamente le proporzioni delle immagini, segui questi passaggi:
```suggestion
            Per usare correttamente le proporzioni delle immagini, segui questi passaggi:
```

2024-01-10 10:13 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/proporzioni.yaml
> +            1. **identifica** le proporzioni originali dell'immagine, utilizzando un editor di immagini o guardando le proprietà;
```suggestion
            1. **identifica** le proporzioni originali dell'immagine, utilizzando un editor di immagini o osservandone le proprietà;
```

2024-01-10 14:22 UTC, zetareticoli commented on src/data/content/design-system/fondamenti/proporzioni.yaml
> +            - mantenere l'**equilibrio** e l'armonia visiva durante il ridimensionamento dell'immagine;
@danielaiozzo mettiamo una "," prima del "se serve"?

2024-01-23 10:34 UTC, Fupete commented on src/data/content/design-system/fondamenti/proporzioni.yaml
> +            Quando si ridimensiona un'immagine, è essenziale mantenere questo rapporto per **prevenire distorsioni**. Ad esempio, un'immagine con un rapporto di 16:9 avrà una larghezza 16 volte super
Corretta questa per me si può mergiare @zetareticoli , e quanto sotto magari aggiungerlo in futuro. (cc @danielaiozzo )

2024-01-23 14:40 UTC, zetareticoli commented on src/data/content/design-system/fondamenti/proporzioni.yaml
> +            Per usare correttamente le proporzioni delle immagini, segui questi passaggi:
Non va troppo sul tecnico? Nel senso, non stiamo parlando di come realizzarlo nel codice, ma solo dando indicazioni generali. Forse al punto 3. è sufficiente fare riferimento al "tieni il focus sempre al centro". Che ne pensi?

2024-01-23 15:02 UTC, Fupete commented on src/data/content/design-system/fondamenti/proporzioni.yaml
> +            Per usare correttamente le proporzioni delle immagini, segui questi passaggi:
Il mio dubbio è che diamo indicazioni comunque tecniche (sui tagli delle immagini in programmi di grafica), ma non è detto che invece l'immagine non serva intera e/o magari in più tagli per una corretta gestione responsive. Forse riformulerei prevedendo questa possibilità.

2024-01-24 09:59 UTC, zetareticoli commented on src/data/content/design-system/fondamenti/proporzioni.yaml
> +            Per usare correttamente le proporzioni delle immagini, segui questi passaggi:
Ho riformulato il punto 3, cercando di essere più generico a proposito delle indicazioni di ridimensionamento. /cc @danielaiozzo

2024-01-24 10:05 UTC, danielaiozzo approved these changes

2024-01-25 10:52 UTC, zetareticoli commented on src/data/content/design-system/fondamenti/proporzioni.yaml
> +            Per usare correttamente le proporzioni delle immagini, segui questi passaggi:
@Fupete appena puoi, rivedi la parte "incriminata" 👍

2024-01-29 15:48 UTC, Fupete approved these changes

2024-01-29 16:04 UTC, merged