fix: archive tags alignment
italia/designers.italia.it pull request #1172
Opened 2024-01-18 11:14 UTC by zetareticoli

Minor changes to archive tags list:

- Decreased label font-size
- Applied `text-secondary`
- Removed left padding on all devices

2024-01-22 08:09 UTC, Fupete commented
@zetareticles the size of the label comes from its nature as a heading. We chose not to change the size of the headings with css to be fully example of respecting the structure of the headings (a11y). I would like to keep it that way.

2024-01-22 08:11 UTC, Fupete requested changes
FYI https://github.com/italia/designers.italia.it/pull/1172#issuecomment-1903455064

2024-01-24 11:45 UTC, zetareticoli commented
> @zetareticoli the size of the label comes from its nature as a heading. We chose not to change the size of the headings with css to be fully example of respecting the structure of the headings (a11y). I would like to keep it that way.

Removed custom heading class and color.

Left extra padding cleanup.

2024-01-25 11:00 UTC, Fupete approved these changes

2024-01-25 11:18 UTC, merged