feat: new service design kit
italia/designers.italia.it pull request #1189
Opened 2024-02-06 09:23 UTC by Fupete

2024-02-06 17:47 UTC, Fupete commented on src/data/content/risorse-per-progettare/progettare/processi-di-servizio/rappresenta-i-flussi-di-servizio.yaml
> +Permette di pianificare le risorse necessarie all’erogazione di un servizio, mostrare i processi agli stakeholder o formare il personale, fornendo una mappatura chiara di ruoli e responsabilità; inol
@ilascar @danielaiozzo è sbagliata l'indentazione di questi paragrafi che seguono dentro questo campo markdown. Devono essere allineati con "La service..." della riga 189 per rimanere dentro il campo `text: |`

2024-02-13 15:23 UTC, danielaiozzo approved these changes

2024-02-14 08:49 UTC, Fupete commented on src/data/content/risorse-per-progettare/progettare/processi-di-servizio.yaml
> +            Fa parte di un servizio digitale anche tutto ciò che accade "dietro le quinte", sia a livello di attori coinvolti che di processi tecnologici (back-stage). Anche questo ambito è fondament
```suggestion
            Fa parte di un servizio digitale anche tutto ciò che accade "dietro le quinte", sia a livello di attori coinvolti che di processi tecnologici (backstage). Anche questo ambito è fondamentale poiché consente l’erogazione mediante i punti di contatto (touchpoint) che intermediano la fruizione dell’utente sui canali digitali o analogici 
```

2024-02-14 08:51 UTC, Fupete commented on src/data/content/risorse-per-progettare/progettare/processi-di-servizio.yaml
> +            (front-stage).
```suggestion
            (frontstage). 
```

2024-02-14 08:54 UTC, Fupete commented on src/data/content/risorse-per-progettare/progettare/processi-di-servizio/rappresenta-i-flussi-di-servizio.yaml
> +            degli utenti e gli scenari d’uso, la service blueprit permette di progettare il servizio e i suoi processi.
```suggestion
            degli utenti e gli scenari d’uso, la service blueprint permette di progettare il servizio e i suoi processi.  
```

2024-02-14 08:55 UTC, Fupete commented on src/data/content/risorse-per-progettare/progettare/processi-di-servizio/rappresenta-i-flussi-di-servizio.yaml
> +            srBefore: "Scarica ODT " #C OPEN FILE FORMAT FOR SCREEN READER ARIA LABEL, eg. PDF, ODX, ...
```suggestion
            # srBefore: "Scarica ODT " #C OPEN FILE FORMAT FOR SCREEN READER ARIA LABEL, eg. PDF, ODX, ...
```

2024-02-14 08:55 UTC, Fupete commented on src/data/content/risorse-per-progettare/progettare/processi-di-servizio/rappresenta-i-flussi-di-servizio.yaml
> +            # srAfter: (si apre in una nuova finestra) # FOR SCREEN READER ARIA LABEL
```suggestion
            srAfter: (si apre in una nuova finestra) # FOR SCREEN READER ARIA LABEL
```

2024-02-14 08:56 UTC, Fupete commented on src/data/content/risorse-per-progettare/progettare/processi-di-servizio/rappresenta-i-flussi-di-servizio.yaml
> +            text: Svolgi sessioni collaborative online con un software open source #C
```suggestion
            text: Svolgi sessioni collaborative online su una lavagna tldraw #C
```

2024-02-14 08:57 UTC, Fupete commented on src/data/content/risorse-per-progettare/progettare/processi-di-servizio/rappresenta-i-flussi-di-servizio.yaml
> +              - icon: sprites.svg#it-file-ods #I USE IF POSSIBLE FILE FORMAT ICONS
```suggestion
              - icon: sprites.svg#it-external-link #I USE IF POSSIBLE FILE FORMAT ICONS
```

2024-02-14 08:57 UTC, Fupete commented on src/data/content/risorse-per-progettare/progettare/processi-di-servizio/rappresenta-i-flussi-di-servizio.yaml
> +                url: /files/resources/risorse-per-progettare/progettare/architettura-informazione/individua-contenuti/DI-Scenari-d-uso.ods #M
```suggestion
                url: https://www.tldraw.com/v/XU_xQbcKHayZdx0KIaUmB?viewport=-9185,-4968,14400,7790&page=page:page #M
```

2024-02-15 09:56 UTC, danielaiozzo requested changes

2024-02-15 09:56 UTC, danielaiozzo commented on src/data/content/risorse-per-progettare/progettare/processi-di-servizio/rappresenta-i-flussi-di-servizio.yaml
> +            url: https://www.tldraw.com/v/XU_xQbcKHayZdx0KIaUmB?viewport=-9185,-4968,14400,7790&page=page:page #M
```suggestion
            url: https://www.tldraw.com/v/7lgxRKdEPtrhvHBhej0qx?viewport=-8437,-4079,7152,3704&page=page:page #M
```

2024-02-15 09:56 UTC, danielaiozzo commented on src/data/content/risorse-per-progettare/progettare/processi-di-servizio/rappresenta-i-flussi-di-servizio.yaml
> +                url: https://www.tldraw.com/v/XU_xQbcKHayZdx0KIaUmB?viewport=-9185,-4968,14400,7790&page=page:page #M
```suggestion
                url: https://www.tldraw.com/v/7lgxRKdEPtrhvHBhej0qx?viewport=-8437,-4079,7152,3704&page=page:page #M
```

2024-02-15 09:56 UTC, danielaiozzo commented on src/data/content/risorse-per-progettare/progettare/processi-di-servizio/rappresenta-i-flussi-di-servizio.yaml
> +            url: https://www.figma.com/file/Kzx0P8cZVdiCEjTmBHAePO/SBP_Designers-Italia?type=whiteboard&node-id=0%3A1&t=h32dl1Snof2HyGB6-1 #M
```suggestion
            url: https://www.figma.com/file/Kzx0P8cZVdiCEjTmBHAePO/DI-Service-Blueprint?type=whiteboard&node-id=0%3A1&t=mPvsx6UO0c2ShrIP-1 #M
```

2024-02-15 09:56 UTC, danielaiozzo commented on src/data/content/risorse-per-progettare/progettare/processi-di-servizio/rappresenta-i-flussi-di-servizio.yaml
> +                url: https://www.figma.com/file/Kzx0P8cZVdiCEjTmBHAePO/SBP_Designers-Italia?type=whiteboard&node-id=0%3A1&t=h32dl1Snof2HyGB6-1 #M
```suggestion
                url: https://www.figma.com/file/Kzx0P8cZVdiCEjTmBHAePO/DI-Service-Blueprint?type=whiteboard&node-id=0%3A1&t=mPvsx6UO0c2ShrIP-1 #M
```

2024-02-15 10:44 UTC, Fupete commented
@danielaiozzo il link della risorsa figjam è sbagliato. Vedi thread slack. Metto in draft per ora.

2024-02-15 10:47 UTC, danielaiozzo commented
> @danielaiozzo il link della risorsa figjam è sbagliato. Vedi thread slack. Metto in draft per ora.

yes, è l'unica che rimane da modificare in attesa di capire come gestire gli accessi

2024-02-16 12:21 UTC, danielaiozzo approved these changes

2024-02-19 11:38 UTC, merged