docs: `Modal` component
italia/designers.italia.it pull request #1195
Opened 2024-02-07 16:38 UTC by zetareticoli

The `Modal` component page.

2024-02-12 14:59 UTC, danielaiozzo requested changes

2024-02-12 14:59 UTC, danielaiozzo commented on src/data/content/design-system/componenti/modal.yaml
> +              - Usa un titolo semplice che sintetizzi lo scopo della finestra modale;
```suggestion
              - Usa un titolo semplice che sintetizza lo scopo della finestra modale e l'azione richiesta;
```

2024-02-12 14:59 UTC, danielaiozzo commented on src/data/content/design-system/componenti/modal.yaml
> +              - Spiega all'utente cosa fare e perché tramite una breve descrizione.
```suggestion
              - Inserisci ulteriori informazioni su cosa fare e perché tramite una breve descrizione.
              - Fai in modo che ci sia accordo fra il verbo che usi per la CTA dell'azione primaria e il verbo che usi nel titolo della modale. 
              
```

2024-02-13 14:43 UTC, danielaiozzo requested changes

2024-02-13 14:43 UTC, danielaiozzo commented on src/data/content/design-system/componenti/modal.yaml
> +              Usa il [tooltip](/design-system/componenti/tooltip) o il [popover](/design-system/componenti/popover) per spiegare una funzione specifica o fornire informazioni aggiuntive, sono meno in
```suggestion
              Usa il [tooltip](/design-system/componenti/tooltip) o il [popover](/design-system/componenti/popover) per spiegare una funzione specifica o fornire informazioni aggiuntive: sono meno invasive di una finestra modale e si possono attivare in diversi modi.
```

2024-02-13 14:43 UTC, danielaiozzo commented on src/data/content/design-system/componenti/modal.yaml
> +              - Fai in modo che ci sia accordo fra il verbo che usi per la CTA dell'azione primaria e il verbo che usi nel titolo della modale.
```suggestion
              - Fai in modo che ci sia accordo fra il verbo che usi per la CTA (call to action) dell'azione primaria e il verbo che usi nel titolo della modale. 
```

2024-02-16 14:26 UTC, danielaiozzo approved these changes

2024-02-16 14:52 UTC, Fupete commented on src/data/content/design-system/componenti/modal.yaml
> +              - Usare un tag <h2> per il titolo della finestra modale in quanto i suoi contenuti sono separati dalla pagina;
```suggestion
              - Usare un tag `<h2>` per il titolo della finestra modale in quanto i suoi contenuti sono separati dalla struttura della pagina; 
              - Usare la semantica `<button>` per l'eventuale pulsante che ne attiva l'apertura, essendo un'azione in pagina;
              - Validare l'interazione da tastiera e con lettori di schermo, in particolar modo rispetto all'ordine degli elementi e a possibili trappole del focus.    
```

2024-02-16 14:53 UTC, Fupete commented on src/data/content/design-system/componenti/modal.yaml
> +              - Le finestre modali possono essere chiuse in diversi modi: tramite l'icona "X" in alto a destra, tramite un pulsante di annullamento o semplicemente cliccando al di fuori della finestr
```suggestion
              - Le finestre modali possono essere chiuse in diversi modi: tramite l'icona "X" in alto a destra, tramite un pulsante di annullamento o chiusura, o semplicemente cliccando al di fuori della finestra modale.
```

2024-02-16 14:54 UTC, Fupete reviewed
@zetareticoli @danielaiozzo fatto salvo le integrazioni suggerite per me è pronta.

2024-02-16 14:56 UTC, danielaiozzo commented
> @zetareticoli @danielaiozzo fatto salvo le integrazioni suggerite per me è pronta.

@Fupete ho approvato le tue suggestion, idem

2024-02-16 15:03 UTC, merged