content(ds): review `Come iniziare/Per designer`
italia/designers.italia.it pull request #1203
Opened 2024-02-09 08:40 UTC by Fupete

2024-02-13 09:57 UTC, danielaiozzo requested changes

2024-02-13 09:57 UTC, danielaiozzo commented on src/data/content/design-system/come-iniziare/per-designer.yaml
> +            La conversione tra il formato Figma, nativo di UI Kit Italia, e il ["formato aperto" Sketch](https://github.com/sketch-hq/sketch-document), è realizzata grazie al convertitore open source
```suggestion
            La conversione tra il formato Figma, nativo di UI Kit Italia, e il ["formato aperto" Sketch](https://github.com/sketch-hq/sketch-document), è realizzata grazie al convertitore open source “fig2sketch”. **Il processo di conversione è automatizzato e a disposizione della community** attraverso un repository template e un'azione pubblicata nel marketplace GitHub Actions. 
```

2024-02-13 11:51 UTC, gianvitofanelli commented
I have two proposals related to the page layout and texts.

## Proposal 1
<img width="770" alt="Screenshot 2024-02-13 at 12 41 21" src="https://github.com/italia/designers.italia.it/assets/30351061/7cf2a73a-4589-4861-a4d5-a6c2e1dce886">
I'd slightly change the spacing here; for instance, the CTA "Leggi la notizia" refers to "Design system: pubblicata la versione ufficiale del kit UI," but it's closer to the paragraph below (Versione corrente). I think it should be closer to the news. I propose reducing the spacing between the news and the call to action or increasing the spacing between the paragraphs (news, versione corrente, altri formati e changelog).

## Proposal 2
<img width="775" alt="Screenshot 2024-02-13 at 12 48 02" src="https://github.com/italia/designers.italia.it/assets/30351061/8089c0eb-8123-4ee5-b2f2-ad7537feb0f2">
All the lines (except the first one) in these lists should start with a lowercase letter since the lines end with semicolons.

2024-02-13 12:05 UTC, Fupete commented
@gianvitofanelli maiuscole corrette. Spaziature paragrafi in caso apri una issue dedicata di styling, questa PR è solo sui contenuti.

2024-02-13 13:06 UTC, zetareticoli approved these changes

2024-02-13 14:46 UTC, danielaiozzo submitted a review, later dismissed

2024-02-13 14:46 UTC, danielaiozzo commented on src/data/content/design-system/come-iniziare/per-designer.yaml
> +            Questa è **la versione 3 di UI Kit Italia**, risorsa ufficiale del design system del Paese. L’insieme di fondamenti e componenti utili ai designer per progettare e prototipare siti intern
```suggestion
            Questa è **la versione 3 di UI Kit Italia**, risorsa ufficiale del design system del Paese: l’insieme di fondamenti e componenti utili ai designer per progettare e prototipare siti e servizi digitali della Pubblica Amministrazione che rispettano le norme e semplificano la vita dei cittadini.
```

2024-02-16 17:05 UTC, Fupete commented
@danielaiozzo ultima review e approvazione e mergiamo anche questa.

2024-02-16 17:18 UTC, danielaiozzo approved these changes

2024-02-16 17:18 UTC, merged