content(ds): review `Fondamenti: Accessibilità`
italia/designers.italia.it pull request #1208
Opened 2024-02-12 15:53 UTC by Fupete

2024-02-15 10:15 UTC, Fupete commented on src/data/content/design-system/fondamenti/accessibilita.yaml
> +            **Per svolgere queste le valutazioni è possibile isolare l'anteprima del componente in una  finestra dedicata**, con il pulsante in alto a destra dell'anteprima. Questa funzionalità perme
```suggestion
            **Per svolgere i test è possibile isolare l'anteprima del componente in una finestra dedicata**, con il pulsante in alto a destra dell'anteprima. Questa funzionalità permette di giudicare le caratteristiche intrinseche del componente isolate dal contesto documentazione, semplificando la necessità di implementare ambienti di test ad hoc.
```

2024-02-15 11:12 UTC, zetareticoli approved these changes

2024-02-15 16:22 UTC, danielaiozzo requested changes

2024-02-15 16:22 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/accessibilita.yaml
> +              1. **Visivamente accessibile** - Uso e contrasto colori, leggibilità
```suggestion
              1. **Visivamente accessibile** - uso e contrasto colori, leggibilità
```

2024-02-15 16:22 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/accessibilita.yaml
> +              2. **Amichevole con i lettori di schermo** - Struttura titolazioni, etichette e testi alternativi
```suggestion
              2. **Amichevole con i lettori di schermo** - struttura titolazioni, etichette e testi alternativi
```

2024-02-15 16:22 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/accessibilita.yaml
> +              3. **Navigabile** - Focus, struttura, navigazione da tastiera o altri device
```suggestion
              3. **Navigabile** - focus, struttura, navigazione da tastiera o altri device
```

2024-02-15 16:22 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/accessibilita.yaml
> +              4. **Comprensibile** - Comprensibile, prevedibile, gestione semplice dell'errore
```suggestion
              4. **Comprensibile** - comprensibile, prevedibile, gestione semplice dell'errore
```

2024-02-15 16:22 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/accessibilita.yaml
> +            Le soluzioni "minime" suggerite per l'utilizzo durante lo sviluppo sono:
```suggestion
            Le soluzioni "minime" suggerite per l'uso durante lo sviluppo sono:
```

2024-02-16 17:02 UTC, Fupete commented
@danielaiozzo ultima review e approva in caso, che è rimasta pending una tua review di modifica per poter mergiare.

2024-02-16 17:04 UTC, danielaiozzo approved these changes

2024-02-16 17:04 UTC, merged