docs: `Badge` componente
italia/designers.italia.it pull request #1210
Opened 2024-02-13 16:27 UTC by zetareticoli

The `Badge` component page.

2024-02-15 15:26 UTC, danielaiozzo requested changes

2024-02-15 15:26 UTC, danielaiozzo commented on src/data/content/design-system/componenti/badge.yaml
> +              Un badge è utilizzato per evidenziare un'informazione o uno stato in un certo contesto. Può essere adoperato per fornire dettagli aggiuntivi, indicare una novità o un cambiamento.
```suggestion
              Un badge è utilizzato per evidenziare un'informazione o uno stato in un certo contesto. Può essere adoperato per fornire dettagli aggiuntivi, indicare una novità o un cambio di stato. 
```

2024-02-15 15:26 UTC, danielaiozzo commented on src/data/content/design-system/componenti/badge.yaml
> +              Può essere usato in vari modi, come per mostrare il numero di notifiche non lette, segnare qualcosa di nuovo o importante, o per visualizzare un breve stato o un'etichetta.
```suggestion
              Può essere usato in vari modi, come per mostrare il numero di notifiche non lette, un breve stato o un'etichetta, o segnalare qualcosa di nuovo o importante.
```

2024-02-15 15:26 UTC, danielaiozzo commented on src/data/content/design-system/componenti/badge.yaml
> +              - Usa il badge per mostrare numeri (come il numero di notifiche non lette) o per visualizzare brevi etichette o stati;
```suggestion
              - Usa il badge per mostrare numeri correlati a un altro elemento di interfaccia (come il numero di notifiche non lette) o per mostrare etichette o stati molto brevi in termini di numero di caratteri;
```

2024-02-15 15:26 UTC, danielaiozzo commented on src/data/content/design-system/componenti/badge.yaml
> +              - Limita il numero di badge presenti nella stessa pagina;
```suggestion
              - Limitare il numero di badge presenti nella stessa pagina;
```

2024-02-16 14:58 UTC, Fupete commented on src/data/content/design-system/componenti/badge.yaml
> +              Può essere usato in vari modi, come per mostrare il numero di notifiche non lette, un breve stato o un'etichetta, o segnalare qualcosa di nuovo o importante.
```suggestion
              Può essere usato in vari modi, come per mostrare il numero di notifiche non lette, un breve messaggio di stato o un'etichetta, o segnalare qualcosa di nuovo o importante.
```

2024-02-16 15:00 UTC, Fupete commented on src/data/content/design-system/componenti/badge.yaml
> +              ### Alternative
@zetareticoli forse segnalerei Chips come prima alternativa, quando vuoi ad esempio segnalare l'appartenenza di un contenuto a una ontologia di argomenti (tag).

2024-02-16 15:02 UTC, Fupete commented on src/data/content/design-system/componenti/badge.yaml
> +              - Limitare il numero di badge presenti nella stessa pagina;
```suggestion
              - Limitare il numero di badge presenti nella stessa pagina;
              - Utilizzare la corretta semantica HTML rispetto a un lettore di schermo se il contenuto o il contesto non è autoesplicativo, ad esempio per un badge numerico utilizzando testo nascosto o etichette `aria` per spiegare a cosa si riferisce;
```

2024-02-16 15:03 UTC, Fupete commented on src/data/content/design-system/componenti/badge.yaml
>              title: Comportamento
Vogliamo indicare la possibilità che contenga un link? Nel caso di numero di nuove notifiche ad es.? O diventa complesso/fuorviante @zetareticoli secondo te?

2024-02-16 15:03 UTC, Fupete commented on src/data/content/design-system/componenti/badge.yaml
> +              - Limitare il numero di badge presenti nella stessa pagina;
@danielaiozzo vedi se rifrasare meglio...

2024-02-16 15:04 UTC, Fupete reviewed
@zetareticoli @danielaiozzo fatto salvo i commenti sopra per me è apposto.

2024-02-16 15:58 UTC, zetareticoli commented on src/data/content/design-system/componenti/badge.yaml
>              title: Comportamento
Ok, lo aggiungo al comportamento, effetivamente c'è anche la variante cliccabile

2024-02-16 17:07 UTC, Fupete approved these changes

2024-02-19 08:55 UTC, danielaiozzo approved these changes

2024-02-19 08:55 UTC, merged