docs: `Datepicker` component
italia/designers.italia.it pull request #1214
Opened 2024-02-15 12:11 UTC by zetareticoli

The `Datepicker` component page.

2024-02-19 08:58 UTC, danielenole commented on src/data/content/design-system/componenti/datepicker.yaml
> +              Il componente datepicker condivide la maggior parte degli elementi con [input](/design-system-/componenti/input), essendo basato su esso.
Il componente datepicker è basato sul componente [input](/design-system-/componenti/input) e ne condivide la maggior parte degli elementi.

2024-02-19 09:01 UTC, danielenole commented on src/data/content/design-system/componenti/datepicker.yaml
> +              - Usa i componenti [input](/design-system/componenti/input) (mese e giorno in formato numerico) e [select](/design-system/componenti/select) (anno) nel caso di date familiari, come la d
Nel caso di date familiari agli utenti, come la data di nascita, e quando non è importante sapere il giorno della settimana, puoi usare il componente [input](/design-system/componenti/input) per il mese e il giorno in formato numerico e il componente [select](/design-system/componenti/select) per l'anno.

2024-02-19 09:07 UTC, danielenole commented on src/data/content/design-system/componenti/datepicker.yaml
> +              Utilizza il componente Datepicker quando gli utenti hanno bisogno di un calendario, ad esempio per programmare un evento o per sapere il giorno della settimana. Questo facilita la scelt
Utilizza il componente Datepicker quando gli utenti hanno bisogno di selezionare una data all'interno di un calendario, ad esempio per prenotare un appuntamento o filtrare una lista di eventi.

2024-02-19 09:09 UTC, danielenole commented on src/data/content/design-system/componenti/datepicker.yaml
> +              - Se necessario, gli utenti possono anche inserire una data manualmente;
- Permetti agli utenti di inserire una data anche manualmente;

2024-02-19 09:10 UTC, danielenole commented on src/data/content/design-system/componenti/datepicker.yaml
> +              - Gli utenti possono navigare attraverso i mesi utilizzando le frecce presenti nel calendario.
- Permetti agli utenti di sfogliare i mesi utilizzando le frecce presenti nel calendario.

2024-02-19 09:13 UTC, danielenole commented on src/data/content/design-system/componenti/datepicker.yaml
> +              - Fornisci il suggerimento del formato data `gg/mm/aaaa` per aiutare gli utenti a inserirlo correttamente se scelgono di non utilizzare il calendario.
- Fornisci il suggerimento del formato `gg/mm/aaaa` per aiutare gli utenti a inserire correttamente una data se scelgono di non utilizzare la selezione a calendario.

2024-02-19 09:29 UTC, danielenole commented on src/data/content/design-system/componenti/datepicker.yaml
> +              5. **testo di supporto**(opzionale): fornisce eventuali indicazioni aggiuntive.
5. **testo di supporto** (opzionale): fornisce eventuali indicazioni aggiuntive su come compilare il campo.

2024-02-19 09:43 UTC, danielenole requested changes

2024-02-19 09:43 UTC, danielenole commented on src/data/content/design-system/componenti/datepicker.yaml
> +              Utilizza il componente Datepicker quando gli utenti hanno bisogno di un calendario, ad esempio per programmare un evento o per sapere il giorno della settimana. Questo facilita la scelt
```suggestion
              Utilizza il componente Datepicker quando gli utenti hanno bisogno di un calendario, ad esempio per programmare un evento o per sapere il giorno della settimana. Questo facilita la scelta della data.
```

2024-02-19 09:43 UTC, danielenole commented on src/data/content/design-system/componenti/datepicker.yaml
> +              - Usa i componenti [input](/design-system/componenti/input) (mese e giorno in formato numerico) e [select](/design-system/componenti/select) (anno) nel caso di date familiari, come la d
```suggestion
              - Nel caso di date familiari agli utenti, come la data di nascita, e quando non è importante sapere il giorno della settimana, puoi usare il componente [input](/design-system/componenti/input) per il mese e il giorno in formato numerico e il componente [select](/design-system/componenti/select) per l'anno.
```

2024-02-19 09:43 UTC, danielenole commented on src/data/content/design-system/componenti/datepicker.yaml
> +              - Se necessario, gli utenti possono anche inserire una data manualmente;
```suggestion
              - Permetti agli utenti di inserire una data anche manualmente;
```

2024-02-19 09:43 UTC, danielenole commented on src/data/content/design-system/componenti/datepicker.yaml
> +              - Gli utenti possono navigare attraverso i mesi utilizzando le frecce presenti nel calendario.
```suggestion
              - Permetti agli utenti di sfogliare i mesi utilizzando le frecce presenti nel calendario.
```

2024-02-19 09:43 UTC, danielenole commented on src/data/content/design-system/componenti/datepicker.yaml
> +              - Fornisci il suggerimento del formato data `gg/mm/aaaa` per aiutare gli utenti a inserirlo correttamente se scelgono di non utilizzare il calendario.
```suggestion
              - Fornisci il suggerimento del formato `gg/mm/aaaa` per aiutare gli utenti a inserire correttamente una data se scelgono di non utilizzare la selezione a calendario.
```

2024-02-19 09:43 UTC, danielenole commented on src/data/content/design-system/componenti/datepicker.yaml
> +              Il componente datepicker condivide la maggior parte degli elementi con [input](/design-system-/componenti/input), essendo basato su esso.
```suggestion
              Il componente datepicker è basato sul componente [input](/design-system-/componenti/input) e ne condivide la maggior parte degli elementi.
```

2024-02-19 09:43 UTC, danielenole commented on src/data/content/design-system/componenti/datepicker.yaml
> +              5. **testo di supporto**(opzionale): fornisce eventuali indicazioni aggiuntive.
```suggestion
              5. **testo di supporto** (opzionale): fornisce eventuali indicazioni aggiuntive.
```

2024-02-19 15:00 UTC, danielenole approved these changes

2024-02-20 15:58 UTC, Fupete approved these changes

2024-02-20 16:12 UTC, merged