docs: `Timepicker` component
italia/designers.italia.it pull request #1218
Opened 2024-02-16 10:46 UTC by zetareticoli

The `Timepicker` component page.

2024-02-19 14:18 UTC, danielenole requested changes

2024-02-19 14:18 UTC, danielenole commented on src/data/content/design-system/componenti/timepicker.yaml
> +              Cliccando sul componente si attiva prima il campo dedicato all'ora.
```suggestion
              Cliccando sul componente si apre un menu a tendina per le ore e uno per i minuti. Il campo ore è il primo attivo. Dopo aver selezionato l'ora, si attiva il campo minuti. 
```

2024-02-19 14:18 UTC, danielenole commented on src/data/content/design-system/componenti/timepicker.yaml
> +
```suggestion
Le ore e i minuti possono essere selezionati al click/tap sulle opzioni nei menu a tendina oppure inseriti manualmente tramite inserimento a tastiera.
```

2024-02-19 14:18 UTC, danielenole commented on src/data/content/design-system/componenti/timepicker.yaml
> +              Per spostare tra il campo ora e minuti si possono usare i tasti freccia destra/sinistra oppure il tasto TAB ⇥.
```suggestion
              Per spostare la selezione tra il campo ore e il campo minuti si possono usare i tasti freccia destra/sinistra oppure il tasto TAB ⇥.
```

2024-02-20 11:28 UTC, zetareticoli commented on src/data/content/design-system/componenti/timepicker.yaml
> +              Suggerisci il formato orario, nel caso di differenza tra AM e PM.
Volevo intendere che se si usa un formato orario in AM o PM, andrebbe suggerito il formato da scrivere in numeri. Se è criptico, rimuoviamo.

2024-02-20 16:10 UTC, Fupete approved these changes

2024-02-20 16:13 UTC, zetareticoli reviewed
Per me sono 👍

2024-02-20 17:08 UTC, danielenole approved these changes

2024-02-20 17:08 UTC, merged