docs: `Notifications` page
italia/designers.italia.it pull request #1229
Opened 2024-02-19 16:05 UTC by zetareticoli

The `Notifications` componente page.

2024-02-20 16:05 UTC, zetareticoli commented
@danielenole puoi iniziare la review dei testi, anche se mancano le immagini

2024-02-22 13:22 UTC, danielenole requested changes

2024-02-22 13:22 UTC, danielenole commented on src/data/content/design-system/componenti/notifications.yaml
> +              - Usa il componente **[Alert](/design-system/componenti/alert)** per mostrare messaggi di avviso importanti che richiedono l’attenzione dell’utente.
```suggestion
              - Usa il componente **[Alert](/design-system/componenti/alert)** per mostrare all'utente messaggi di avviso importanti che restano nel corpo della pagina senza scomparire automaticamente.
```

2024-02-22 13:22 UTC, danielenole commented on src/data/content/design-system/componenti/notifications.yaml
> +              Usa il componente Notifiche per aggiornare l'utente su modifiche o aggiornamenti minori all'interno dell'applicazione. Questi messaggi temporanei tendono a scomparire dopo pochi secondi
```suggestion
              Usa il componente Notifiche per aggiornare l'utente su modifiche o aggiornamenti minori all'interno dell'applicazione. Questi messaggi temporanei appaiono in sovrimpressione e tendono a scomparire dopo pochi secondi, quindi potrebbero non essere sempre notati o letti attentamente.
```

2024-02-22 13:22 UTC, danielenole commented on src/data/content/design-system/componenti/notifications.yaml
> +              - Cambia lo stile della notifica in base all'obiettivo del messaggio, usando le diverse opzioni disponibili;
```suggestion
              - Cambia lo stile della notifica in base all'obiettivo del messaggio, usando le diverse varianti disponibili;
```

2024-02-22 13:22 UTC, danielenole commented on src/data/content/design-system/componenti/notifications.yaml
> +              - Usa la descrizione solo per informazioni salienti;
```suggestion
              - Includi una descrizione con informazioni aggiuntive solo quando queste sono importanti e non possono essere riassunte nel titolo della notifica.
```

2024-02-22 13:22 UTC, danielenole commented on src/data/content/design-system/componenti/notifications.yaml
> +              - L'utente può anche chiuderla manualmente, se presente un'icona di chiusura;
```suggestion
              - L'utente può chiudere la notifica manualmente prima che scompaia automaticamente, se presente un'icona di chiusura;
```

2024-02-27 11:29 UTC, danielenole requested changes
segno come pending perché nella preview non vedo le immagini della sezione specifiche di design

![Schermata 2024-02-27 alle 12 28 39](https://github.com/italia/designers.italia.it/assets/102873965/d0683bec-7dfd-4914-b1fc-c58d58b369b2)

2024-02-28 08:11 UTC, danielenole approved these changes

2024-02-29 16:22 UTC, danielenole approved these changes

2024-02-29 17:15 UTC, merged