docs: `Sidebar` component
italia/designers.italia.it pull request #1234
Opened 2024-02-20 15:02 UTC by zetareticoli

The `Sidebar` componente page.

2024-02-21 15:51 UTC, zetareticoli commented
@danielenole ho preparato i contenuti, può iniziare la review in attesa che completi specifiche e anatomia 👍

2024-02-21 16:13 UTC, zetareticoli commented
@Fupete non ti ho taggato come reviewer perché aspetto di completare la scheda con immagini entro venerdì

2024-02-22 13:49 UTC, danielenole commented
Ho anche modificato il sottotitolo di pagina e descrizione SEO in "Barra di navigazione laterale che include liste di link diretti o annidati"

2024-02-27 11:25 UTC, danielenole commented
nella scheda progettazione vedo un'immagine che mi sembra essere del componente button e non della sidebar

2024-02-27 11:26 UTC, danielenole requested changes

2024-02-27 11:26 UTC, danielenole commented on src/data/content/design-system/componenti/sidebar.yaml
> +              Il componente sidebar è composto da:
```suggestion
              Il componente sidebar è composto da:
              
```

2024-02-27 11:26 UTC, danielenole commented on src/data/content/design-system/componenti/sidebar.yaml
> +              1.**intestazione**: definisce lo scopo della sidebar;
```suggestion
              1. **intestazione**: definisce lo scopo della sidebar;
```

2024-02-27 11:26 UTC, danielenole commented on src/data/content/design-system/componenti/sidebar.yaml
> +              2.**voce principale**: può essere diretta ad una pagina o annidare altre voci;
```suggestion
              2. **voce principale**: può essere diretta ad una pagina o annidare altre voci;
```

2024-02-27 11:26 UTC, danielenole commented on src/data/content/design-system/componenti/sidebar.yaml
> +              3.**voce annidata**: ha un margine di rientro e un peso visivo inferiore;
```suggestion
              3. **voce annidata**: ha un margine di rientro e un peso visivo inferiore;
```

2024-02-27 11:26 UTC, danielenole commented on src/data/content/design-system/componenti/sidebar.yaml
> +              4.**bordo esterno**: deliminta l'area della sidebar in verticale, può essere a destra o sinistra in base alla posizione del menu;
```suggestion
              4. **bordo esterno**: deliminta l'area della sidebar in verticale, può essere a destra o sinistra in base alla posizione del menu;
```

2024-02-27 11:26 UTC, danielenole commented on src/data/content/design-system/componenti/sidebar.yaml
> +              5.**linea divisoria**: divide le voci principali dalle secondarie;
```suggestion
              5. **linea divisoria**: divide le voci principali dalle secondarie;
```

2024-02-27 11:26 UTC, danielenole commented on src/data/content/design-system/componenti/sidebar.yaml
> +              6.**voce secondaria**: ha un peso visivo minore rispetto alle principali;
```suggestion
              6. **voce secondaria**: ha un peso visivo minore rispetto alle principali;
```

2024-02-28 08:14 UTC, danielenole approved these changes

2024-02-29 15:58 UTC, Fupete approved these changes

2024-02-29 16:27 UTC, danielenole approved these changes

2024-02-29 17:21 UTC, merged