docs: `Steppers` component
italia/designers.italia.it pull request #1237
Opened 2024-02-21 15:54 UTC by zetareticoli

The `Steppers` component page.

2024-02-22 15:42 UTC, danielenole commented
Ho anche aggiornato il titolo e la descrizione del componente (pagina e SEO)

2024-02-22 15:42 UTC, danielenole requested changes

2024-02-22 15:42 UTC, danielenole commented on src/data/content/design-system/componenti/steppers.yaml
> +              Il componente Steppers è perfetto se si deve gestire un processo che richiede vari passaggi, in un progresso lineare.
```suggestion
              Usa il componente Stepper per suddividere i passaggi di una procedura lineare in più schermate e per indicare all'utente l'avanzamento del progresso. 
```

2024-02-22 15:42 UTC, danielenole commented on src/data/content/design-system/componenti/steppers.yaml
> +              - Considera l’uso di **[form](https://www.notion.so/Steppers-2d1e6353e31f451ca89bc3a71ebe9e96?pvs=21)** semplice se un processo ha meno di tre sezioni.
```suggestion
              - Considera l’uso di **[form](https://www.notion.so/Steppers-2d1e6353e31f451ca89bc3a71ebe9e96?pvs=21)** semplice se un processo ha meno di tre passaggi.
```

2024-02-22 15:42 UTC, danielenole commented on src/data/content/design-system/componenti/steppers.yaml
> +              - Usa la navigazione con un [gruppo di pulsanti](https://designsystem.digital.gov/components/button-group/) per avanzare o tornare indietro;
```suggestion
              - Usa la navigazione con un [gruppo di pulsanti](https://designsystem.digital.gov/components/button-group/) per permettere all'utente di avanzare o tornare indietro;
```

2024-02-22 15:42 UTC, danielenole commented on src/data/content/design-system/componenti/steppers.yaml
> +              - Indica sempre dove si trova un utente nel processo, evidenziando il passaggio corrente con un bordo, uno colore di sfondo o uno stile di testo; il passaggio corrente deve essere visiv
```suggestion
              - Indica sempre dove si trova un utente nel processo, evidenziando il passaggio corrente con un bordo, uno colore di sfondo o uno stile di testo. Il passaggio corrente deve essere visivamente prominente e distinguersi sia dai passaggi completati che da quelli in sospeso;
```

2024-02-22 15:42 UTC, danielenole commented on src/data/content/design-system/componenti/steppers.yaml
> +              - Usa la navigazione con un [gruppo di pulsanti](https://designsystem.digital.gov/components/button-group/) per avanzare o tornare indietro;
Il link punta a un DS esterno - è corretto?

2024-02-22 15:42 UTC, danielenole commented on src/data/content/design-system/componenti/steppers.yaml
> +              - Usa un pulsante “Salva” per consentire il salvataggio dei dati durante il processo di compilazione;
```suggestion
              - Includi un pulsante “Salva” per consentire il salvataggio dei dati durante il processo di compilazione.
```

2024-02-22 15:42 UTC, danielenole commented on src/data/content/design-system/componenti/steppers.yaml
> +              - Non usare Steppers per form con logica condizionale, dove il numero dei passaggi potrebbe dipendere dai dati inseriti dall’utente;
```suggestion
              - Non usare lo stepper per form con logica condizionale, dove il numero dei passaggi potrebbe dipendere dai dati inseriti dall’utente;
```

2024-02-22 15:42 UTC, danielenole commented on src/data/content/design-system/componenti/steppers.yaml
> +              - Non usare Steppers in caso di un progresso non lineare, dove il completamento dei passaggi non segue un ordine specifico;
```suggestion
              - Non usare lo stepper in caso di un progresso non lineare, dove il completamento dei passaggi non segue un ordine specifico.
```

2024-02-22 15:42 UTC, danielenole commented on src/data/content/design-system/componenti/steppers.yaml
> +              - Posiziona il titolo del passaggio subito sotto lo stepper, utilizzando un testo coerente con quello presente nell’etichetta;
```suggestion
              - Riproponi il titolo del passaggio subito sotto lo stepper, utilizzando un testo coerente con quello presente nell’etichetta del componente;
```

2024-02-22 15:42 UTC, danielenole commented on src/data/content/design-system/componenti/steppers.yaml
> +              - Mostra il passaggio corrente e il totale a sinistra del titolo. L'uso di un testo come "[passo] di [totale]" accanto al titolo rafforza il numero di passaggi totali e aiuta gli utenti
```suggestion
              - Mostra il numero del passaggio corrente con il totale a sinistra del titolo. L'uso di un testo come "[numero passaggio corrente] di [numero totale dei passaggi] (ad esempio, 2 di 5)" accanto al titolo. Questo aiuta gli utenti a tenere traccia della loro posizione nel processo complessivo.
```

2024-02-27 11:31 UTC, danielenole approved these changes

2024-02-29 16:15 UTC, Fupete approved these changes

2024-02-29 16:30 UTC, danielenole approved these changes

2024-02-29 17:38 UTC, merged