docs: `Toggle` component
italia/designers.italia.it pull request #1238
Opened 2024-02-26 11:06 UTC by zetareticoli

The `Toggle` componente page.

2024-02-28 10:00 UTC, danielenole requested changes

2024-02-28 10:00 UTC, danielenole commented on src/data/content/design-system/componenti/toggles.yaml
> +              Usa etichette chiare per indicare lo stato del toggle.
```suggestion
              Usa etichette chiare per indicare lo stato del toggle e per spiegare all'utente cosa comporta il cambio di stato.
```

2024-02-28 10:00 UTC, danielenole commented on src/data/content/design-system/componenti/toggles.yaml
> +              Evita di usare toggle per azioni che richiedono conferma immediata o che potrebbero avere conseguenze significative se attivate accidentalmente;
```suggestion
              Evita di usare toggle per azioni che richiedono conferma immediata o che potrebbero avere conseguenze significative se attivate accidentalmente.
```

2024-02-28 10:00 UTC, danielenole commented on src/data/content/design-system/componenti/toggles.yaml
> +  description: "È un campo di tipo 'interruttore' che permette di scegliere tra due stati."
```suggestion
  description: "Pulsante di tipo 'interruttore' che permette di scegliere tra due stati."
```

2024-02-28 10:00 UTC, danielenole commented on src/data/content/design-system/componenti/toggles.yaml
> +    subtitle: "È un campo di tipo 'interruttore' che permette di scegliere tra due stati."
```suggestion
    subtitle: "Pulsante di tipo 'interruttore' che permette di scegliere tra due stati."
```

2024-02-28 10:00 UTC, danielenole commented on src/data/content/design-system/componenti/toggles.yaml
> +              Utilizza il componente toggle per dare agli utenti l'opzione di alternare tra due stati, come ON e OFF, oppure VERO e FALS. Questo è pratico quando vuoi modificare velocemente le impost
```suggestion
              Usa il componente Toggle per dare agli utenti l'opzione di alternare tra due stati, come ON/OFF oppure VERO/FALSO.
```

2024-02-28 10:00 UTC, danielenole commented on src/data/content/design-system/componenti/toggles.yaml
> +              Il toggle è particolarmente utile quando lo spazio a disposizione è poco, adattandosi bene all’uso su dispositivi mobile.
```suggestion
              È un'opzione utile per permettere di modificare velocemente le impostazioni di un account o le preferenze di un servizio, soprattutto quando lo spazio a disposizione è poco, come sui dispositivi mobile.
```

2024-03-01 10:39 UTC, Fupete approved these changes

2024-03-01 11:09 UTC, danielaiozzo requested changes
@Fupete @zetareticoli a mio avviso andrebbe variato il nome al singolare

2024-03-01 11:09 UTC, danielaiozzo commented on src/data/content/design-system/componenti/toggles.yaml
> +              Usa il componente Toggles, nel contesto di un modulo ([Form](/design-system/componenti/form/)), per dare agli utenti l'opzione di alternare tra due stati, come ON/OFF oppure VERO/FALSO.
```suggestion
              Usa il componente Toggle nel contesto di un modulo ([Form](/design-system/componenti/form/)), per dare agli utenti l'opzione di alternare tra due stati, come ON/OFF oppure VERO/FALSO.
```

2024-03-01 11:09 UTC, danielaiozzo commented on src/data/content/design-system/componenti/toggles.yaml
> +              - Raggruppa Toggles utilizzando la variante dedicata, assicurandoti che sia chiara la distinzione tra i singoli elementi.
```suggestion
              - Raggruppa più Toggle utilizzando la variante dedicata, assicurandoti che sia chiara la distinzione tra i singoli elementi. 
```

2024-03-01 11:12 UTC, danielaiozzo approved these changes

2024-03-01 11:39 UTC, danielenole approved these changes

2024-03-01 11:46 UTC, merged