content: update `divulgazione e disseminazione`
italia/designers.italia.it pull request #1245
Opened 2024-02-27 14:54 UTC by Fupete

2024-02-28 08:42 UTC, Fupete commented on src/data/content/progetto/divulgazione-e-disseminazione.yaml
> +            Attraverso i nostri interventi e materiali per i corsi di formazione, miriamo a fornire le basi di cultura progettuale agli attori direttamente coinvolti nei processi di trasformazione di
```suggestion
            
            Attraverso i nostri interventi e materiali per i corsi di formazione, miriamo a fornire le basi di cultura progettuale agli attori direttamente coinvolti nei processi di trasformazione digitale dei servizi pubblici. 
```

2024-02-28 09:34 UTC, Fupete commented on src/data/content/progetto/divulgazione-e-disseminazione.yaml
> +            Attraverso i nostri materiali educativi, dedicati all’insegnamento del design in ambito pubblico speriamo che un numero sempre maggiore di persone interessate ad a questi temi possa trova
```suggestion
            
            Attraverso i nostri materiali educativi, dedicati all’insegnamento del design in ambito pubblico speriamo che un numero sempre maggiore di persone interessate ad a questi temi possa trovare spunti utili, e proporre interventi mirati. 
```

2024-02-28 09:35 UTC, Fupete commented on src/data/content/progetto/divulgazione-e-disseminazione.yaml
> +            Partecipiamo ad eventi di divulgazione e networking, sia in qualità di auditori che di oratori, con l’obiettivo di condividere punti di vista ed esperienze attraverso l’ascolto, la collab
```suggestion
            
            Partecipiamo ad eventi di divulgazione e networking, sia in qualità di auditori che di oratori, con l’obiettivo di condividere punti di vista ed esperienze attraverso l’ascolto, la collaborazione e la partecipazione della comunità di designer e developer e grazie ad eventi e conferenze, collaborazioni, community call, contributi esterni sul blog. 
```

2024-02-28 09:35 UTC, Fupete commented on src/data/content/progetto/divulgazione-e-disseminazione.yaml
> +            I nostri materiali mirano ad abilitare queste figure nel comprendere il valore e i benefici di un certo approccio progettuale, e potersi fare ambasciatori, del rispetto delle norme, degli
```suggestion
            
            I nostri materiali mirano ad abilitare queste figure nel comprendere il valore e i benefici di un certo approccio progettuale, e potersi fare ambasciatori, del rispetto delle norme, degli standard di qualità e di un’esperienza di fruizione centrata sul cittadino.
```

2024-02-28 11:26 UTC, danielenole requested changes

2024-02-28 11:26 UTC, danielenole commented on src/data/content/progetto/divulgazione-e-disseminazione.yaml
> +            La community è essenziale in un ambito che cambia così velocemente, una rete diffusa di professionisti esperti sul tema è la chiave per affrontare questa complessità, per promuovere la co
```suggestion
            La community è essenziale in un ambito che cambia così velocemente. Una rete diffusa di professionisti esperti sul tema è la chiave per affrontare questa complessità, per promuovere la collaborazione su temi comuni, imparare da chi ‘opera’ sul campo, incoraggiare la partecipazione e la condivisione di buone pratiche.
```

2024-02-28 11:26 UTC, danielenole commented on src/data/content/progetto/divulgazione-e-disseminazione.yaml
> +            Partecipiamo ad eventi di divulgazione e networking, sia in qualità di auditori che di oratori, con l’obiettivo di condividere punti di vista ed esperienze attraverso l’ascolto, la collab
```suggestion
            Partecipiamo a eventi e conferenze, sia in qualità di uditori che di relatori, con l’obiettivo di condividere punti di vista ed esperienze attraverso l’ascolto, la collaborazione e la partecipazione della comunità di designer e developer. 
```

2024-02-28 11:26 UTC, danielenole commented on src/data/content/progetto/divulgazione-e-disseminazione.yaml
> +            Stabilire pubbliche relazioni con le amministrazioni pubbliche, le in-house e i fornitori privati ci permette di trovare ambasciatori a sostegno del progetto puntando a coinvolgere tutti
```suggestion
            Stabilire pubbliche relazioni con le amministrazioni pubbliche, le in-house e i fornitori privati ci permette di trovare ambasciatori a sostegno del progetto. Puntiamo a coinvolgere tutti quelli che hanno un forte impatto sulla trasformazione digitale dei servizi pubblici, sia a livello centrale che locale.
```

2024-02-28 11:26 UTC, danielenole commented on src/data/content/progetto/divulgazione-e-disseminazione.yaml
> +            I nostri materiali mirano ad abilitare queste figure nel comprendere il valore e i benefici di un certo approccio progettuale, e potersi fare ambasciatori, del rispetto delle norme, degli
```suggestion
            I nostri materiali aiutano queste figure a comprendere il valore e i benefici di un certo approccio progettuale e farsi ambasciatori del rispetto delle norme, degli standard di qualità e di un’esperienza di fruizione centrata sul cittadino.
```

2024-02-28 11:26 UTC, danielenole commented on src/data/content/progetto/divulgazione-e-disseminazione.yaml
> +          L’obiettivo della nostra strategia di divulgazione e disseminazione è quello di guidare la trasformazione digitale dei servizi pubblici attraverso la promozione di una cultura progettuale v
```suggestion
          L’obiettivo della nostra strategia di divulgazione e disseminazione è quello di **promuovere una cultura progettuale virtuosa per i servizi pubblici digitali**. Per questo ci rivolgiamo a tutti coloro che sono coinvolti e che possono fare la differenza nell'ambito della trasformazione digitale della PA: funzionari pubblici, progettisti, sviluppatori e tutta la nostra community.
```

2024-02-28 11:26 UTC, danielenole commented on src/data/content/progetto/divulgazione-e-disseminazione.yaml
> +          dai funzionari pubblici, ai progettisti del futuro, e che possono fare la differenza nell’ambito dei servizi pubblici, la nostra community.
```suggestion
```

2024-02-28 11:26 UTC, danielenole commented on src/data/content/progetto/divulgazione-e-disseminazione.yaml
> +        Crediamo che il cambiamento debba avvenire sia dal basso che dall’alto, per un’azione sinergica mirata da un lato ad incoraggiare ad un approccio virtuoso mettendo a disposizione gli strument
```suggestion
        Crediamo che il cambiamento debba avvenire sia dal basso che dall’alto, per un’azione sinergica mirata da un lato a incoraggiare un approccio virtuoso, mettendo a disposizione gli strumenti per farlo, dall’altro a dare regolamenti e riferimenti chiari e puntuali. Per questo la nostra strategia si articola in quattro aree di opportunità e intervento.
```

2024-02-28 11:29 UTC, ilascar approved these changes

2024-02-28 11:36 UTC, Fupete commented on src/data/content/progetto/divulgazione-e-disseminazione.yaml
> +          - label: Esplora le attività della community #C
@danielenole (cc @ilascar) per coerenza col resto del sito tutte le CTA dei 2° livelli se non ricordo male sono "Scopri...". Mi pare che solo le fasi dei kit e l'accesso agli archivi abbia "Esplora...".

2024-02-28 11:37 UTC, Fupete commented on src/data/content/progetto/divulgazione-e-disseminazione.yaml
> +          - label: Esplora le attività della community #C
(btw no blocking, appena ho tempo in pomeriggio la mergiamo)

2024-02-28 15:43 UTC, Fupete commented on src/data/content/progetto/divulgazione-e-disseminazione.yaml
> +              url: "/community/media/20230215-il-service-design-nella-pa-italiana/" #M
```suggestion
              url: "/community/media/" #M
```

2024-02-28 15:44 UTC, Fupete commented on src/data/content/progetto/divulgazione-e-disseminazione.yaml
> +              url: "/community/media/20230215-il-service-design-nella-pa-italiana/" #M
@ilascar @danielenole controllate il link, dovrebbe mandare a media immagino non a uno specifico... giusto?

2024-02-28 16:00 UTC, ilascar commented
No no è voluto

Inviato da Outlook per iOS<https://aka.ms/o0ukef>
________________________________
Da: Daniele T. ***@***.***>
Inviato: Wednesday, February 28, 2024 4:44:47 PM
A: italia/designers.italia.it ***@***.***>
Cc: Ilaria Scarpellini ***@***.***>; Mention ***@***.***>
Oggetto: Re: [italia/designers.italia.it] content: update `divulgazione e disseminazione` (PR #1245)


@Fupete commented on this pull request.

________________________________

In src/data/content/progetto/divulgazione-e-disseminazione.yaml<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fitalia%2Fdesigners.italia.it%2Fpull%2F1245%23discussion_r1506175409&e=bcb9f84b&h=face11f8&f=n&p=y>:

>
+          ctas:
+            - label: Segui le videolezioni #C
+              url: "/community/media/20230215-il-service-design-nella-pa-italiana/" #M


@ilascar<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Filascar&e=bcb9f84b&h=b7e16db3&f=n&p=y> @danielenole<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fdanielenole&e=bcb9f84b&h=9466a13e&f=n&p=y> controllate il link, dovrebbe mandare a media immagino non a uno specifico... giusto?

—
Reply to this email directly, view it on GitHub<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fitalia%2Fdesigners.italia.it%2Fpull%2F1245%23discussion_r1506175409&e=bcb9f84b&h=face11f8&f=n&p=y>, or unsubscribe<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FBDRI5NCFLJVGOSHD6T76WITYV5GG7AVCNFSM6AAAAABD4ILFJ2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSMBWGYYTCMZQGQ&e=bcb9f84b&h=2dadfe2c&f=n&p=y>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-02-29 11:17 UTC, Fupete commented on src/data/content/progetto/divulgazione-e-disseminazione.yaml
> +                icon: sprites.svg#it-arrow-right #C #I #it-arrow-right | it-external-link for external links
```suggestion
                icon: sprites.svg#it-video #C #I #it-arrow-right | it-external-link for external links
```

2024-03-01 11:39 UTC, merged