docs: `Tooltip` component
italia/designers.italia.it pull request #1246
Opened 2024-02-27 16:46 UTC by zetareticoli

The `Tooltip` component page.

2024-02-29 16:41 UTC, danielenole requested changes

2024-02-29 16:41 UTC, danielenole commented on src/data/content/design-system/componenti/tooltip.yaml
> +              - Usa il [popover](/design-system/componenti/popover) quando hai bisogno di mostrare più informazioni e inserire un link o pulsante;
```suggestion
              - [Popover](/design-system/componenti/popover): se hai bisogno di mostrare più informazioni e inserire un link o pulsante.
```

2024-02-29 16:41 UTC, danielenole commented on src/data/content/design-system/componenti/tooltip.yaml
> +              - Usa il semplice testo di aiuto inline quando si desidera fornire informazioni aggiuntive direttamente nella pagina, senza la necessità di interazione da parte dell'utente.
```suggestion
              - Usa il semplice testo di aiuto inline per fornire informazioni aggiuntive direttamente nella pagina, senza la necessità di interazione da parte dell'utente.
```

2024-02-29 16:41 UTC, danielenole commented on src/data/content/design-system/componenti/tooltip.yaml
> +              - I tooltip dovrebbero contenere solo informazioni supplementari, non essenziali.
```suggestion
              - Non usare i tooltip per informazioni importanti, poiché l'utente potrebbe non vederle.
```

2024-02-29 16:41 UTC, danielenole commented on src/data/content/design-system/componenti/tooltip.yaml
> +              - Se l'utente interagisce con il tooltip (ad esempio, per copiare del testo), questo rimane visibile fino a quando non si sposta il mouse o fa clic altrove;
```suggestion
              - Se l'utente interagisce con il tooltip (ad esempio, per copiare del testo), questo rimane visibile fino a quando non si sposta il mouse o fa clic altrove.
```

2024-03-01 10:38 UTC, Fupete approved these changes

2024-03-01 11:16 UTC, danielaiozzo requested changes

2024-03-01 11:16 UTC, danielaiozzo commented on src/data/content/design-system/componenti/tooltip.yaml
> +              Utilizza il componente Tooltip quando vuoi fornire ulteriori informazioni su un elemento specifico senza sovraccaricare l'interfaccia utente. I Tooltip sono utili quando il loro contenu
```suggestion
              Usa il componente Tooltip quando vuoi fornire ulteriori informazioni su un elemento specifico senza sovraccaricare l'interfaccia utente. I Tooltip sono utili quando il loro contenuto aggiunge valore o aiuta a capire meglio una funzione, ma non è essenziale per l'uso principale dell'elemento. 
```

2024-03-01 11:16 UTC, danielaiozzo commented on src/data/content/design-system/componenti/tooltip.yaml
> +              Ad esempio, possono essere utilizzati per spiegare il significato di un'icona, per fornire un suggerimento su come utilizzare una funzionalità o per mostrare informazioni aggiuntive su
```suggestion
              Ad esempio, i Tooltip possono essere usati per spiegare il significato di un'icona, per fornire un suggerimento su come utilizzare una funzionalità o per mostrare informazioni aggiuntive su un dato o un'opzione.
```

2024-03-01 11:16 UTC, danielaiozzo commented on src/data/content/design-system/componenti/tooltip.yaml
> +              - Il contenuto del Tooltip deve essere conciso, preferibilmente non più di una o due frasi.
```suggestion
              - Il contenuto del Tooltip deve essere conciso, preferibilmente non più di una o due frasi.
              - Data la sua natura di aiuto contestuale non sempre visibile in pagina, il Tooltip non dovrebbe contenere informazioni salienti per l'interazione ma solo aggiunte o specifiche ulteriori  relative all'elemento cui è associato. 
```

2024-03-01 11:21 UTC, danielaiozzo requested changes

2024-03-01 11:21 UTC, danielaiozzo commented on src/data/content/design-system/componenti/tooltip.yaml
> +              - Data la sua natura di aiuto contestuale non sempre visibile in pagina, il Tooltip non dovrebbe contenere informazioni salienti per l'interazione ma solo aggiunte o specifiche ulterior
```suggestion
              - Data la sua natura di aiuto contestuale non sempre visibile in pagina, il Tooltip non dovrebbe contenere informazioni salienti per l'interazione ma solo aggiunte o specifiche ulteriori relative all'elemento cui è associato. 
```

2024-03-01 11:22 UTC, danielaiozzo approved these changes

2024-03-01 11:38 UTC, danielenole approved these changes

2024-03-01 12:03 UTC, merged