content(ds): review `Back to top` component
italia/designers.italia.it pull request #1259
Opened 2024-03-01 10:58 UTC by Fupete

2024-03-05 14:10 UTC, danielenole requested changes

2024-03-05 15:04 UTC, zetareticoli requested changes

2024-03-05 15:04 UTC, zetareticoli commented on src/data/content/design-system/componenti/back-to-top.yaml
> +              - appare in posizione `fixed` nell'angolo in basso a destra della viewport, in sovrimpressione sui contenuti di pagina;
```suggestion
              - Appare in posizione `fixed` nell'angolo in basso a destra della viewport, in sovrimpressione sui contenuti di pagina;
```

2024-03-05 15:04 UTC, zetareticoli commented on src/data/content/design-system/componenti/back-to-top.yaml
> +              - al click/touch o attivazione da tastiera riporta l'utente all'inizio della pagina.
```suggestion
              - Al click/touch o attivazione da tastiera riporta l'utente all'inizio della pagina. 
```

2024-03-06 12:21 UTC, danielenole approved these changes

2024-03-07 13:42 UTC, zetareticoli commented on src/data/content/design-system/componenti/back-to-top.yaml
> +              - Comunicare se possibile l'apparizione del componente e la sua funzione alle tecnologie assistive come i lettori di schermo.
```suggestion
              - Comunicare se possibile la comparsa del componente e la sua funzione alle tecnologie assistive come i lettori di schermo.
```

2024-03-07 14:57 UTC, merged