docs: `Bottomnav` component
italia/designers.italia.it pull request #1264
Opened 2024-03-04 15:56 UTC by zetareticoli

The `Bottomnav` component.

2024-03-06 10:30 UTC, danielenole requested changes

2024-03-06 10:30 UTC, danielenole commented on src/data/content/design-system/componenti/bottomnav.yaml
> +              - Il componente ha un’altezza fissa ed è ancorato al fondo della pagina, occupandone tutta la larghezza.
```suggestion
              - Posiziona il componente fissandolo al fondo della pagina lungo tutta la larghezza del viewport.
              - Includi i collegamenti per navigare alle principali sezioni del sito o dell'app.
```

2024-03-06 10:30 UTC, danielenole commented on src/data/content/design-system/componenti/bottomnav.yaml
> +              - Se le sezioni prevedono notifiche di aggiornamento, puoi combinare il componente [Badge](/design-system/componenti/badge)
```suggestion
              - Se hai bisogno di aggiungere un contatore per eventuali notifiche di aggiornamento, puoi combinare il componente [Badge](/design-system/componenti/badge) sugli elementi del componente BottomNav.
```

2024-03-06 10:30 UTC, danielenole commented on src/data/content/design-system/componenti/bottomnav.yaml
> +              - Limita il numero di sezioni presenti nel menu, non dovrebbero essere più di cinque.
```suggestion
              - Limitare il numero di sezioni ed elementi presenti nella barra del componente. Non dovrebbero essere più di cinque.
```

2024-03-06 10:30 UTC, danielenole commented on src/data/content/design-system/componenti/bottomnav.yaml
> +              - Il componente bottomnav rimane fisso a fondo pagina durante lo scroll;
```suggestion
              - Il componente BottomNav rimane fisso a fondo pagina durante lo scroll;
```

2024-03-06 10:30 UTC, danielenole commented on src/data/content/design-system/componenti/bottomnav.yaml
> +              - Il titolo della voce di menu deve essere composta da una sola parola;
```suggestion
              - I titoli delle voci della barra devono essere composti da una sola parola, dal significato chiaro e intuitivo.
```

2024-03-06 10:30 UTC, danielenole commented on src/data/content/design-system/componenti/bottomnav.yaml
> +              - Usa il componente Header per la navigazione di primo livello con le sezioni principali di un sito o app.
```suggestion
              - **Header (/design-system/componenti/header):** quando vuoi fornire una navigazione di primo livello ancorata in cima al viewport di un sito o una app.
```

2024-03-06 10:30 UTC, danielenole commented on src/data/content/design-system/componenti/bottomnav.yaml
> +              Il componente BottomNav è pensato per la navigazione su dispositivi mobile il cui aspetto ricalca quello di alcune popolari app.
```suggestion
              Usa il componente BottomNav per fornire una barra di navigazione ancorata al fondo della pagina su dispositivi mobile, come avviene sulla maggior parte delle app.
```

2024-03-06 10:30 UTC, danielenole commented on src/data/content/design-system/componenti/bottomnav.yaml
> +              Pul essere utilizzato quando si desidera fornire una navigazione intuitiva su dispositivi mobili.
```suggestion
```

2024-03-06 11:02 UTC, zetareticoli commented on src/data/content/design-system/componenti/bottomnav.yaml
> +              - Il titolo della voce di menu deve essere composta da una sola parola;
@danielenole rimuoviamo totalmente "della barra"?

2024-03-07 15:48 UTC, danielenole requested changes

2024-03-07 15:48 UTC, danielenole commented on src/data/content/design-system/componenti/bottomnav.yaml
> +              4. **numero**(opzionale): se presente, il numero del badge informa sulla presenza di notifiche.
```suggestion
              4. **contatore** (opzionale): se presente, il numero del badge informa sulla presenza di notifiche o aggiornamenti.
```

2024-03-07 16:44 UTC, Fupete commented on src/data/content/design-system/componenti/bottomnav.yaml
> +  description: "Barra di navigazione fissa a fondo pagina per dispositivi mobile"
```suggestion
  description: "Barra di navigazione fissa a fondo pagina per dispositivi mobile."
```

2024-03-07 16:45 UTC, Fupete commented on src/data/content/design-system/componenti/bottomnav.yaml
> +              Usa il componente BottomNav per fornire una barra di navigazione ancorata al fondo della pagina su dispositivi mobile, come avviene sulla maggior parte delle app.
```suggestion
              Usa il componente BottomNav per fornire una barra di navigazione ancorata al fondo della pagina su dispositivi mobile, come avviene sulla maggior parte delle app mobile.
```

2024-03-07 16:45 UTC, Fupete commented on src/data/content/design-system/componenti/bottomnav.yaml
> +              - **Header (/design-system/componenti/header):** quando vuoi fornire una navigazione di primo livello ancorata in cima al viewport di un sito o una app.
```suggestion
              - **[Header](/design-system/componenti/header):** quando vuoi fornire una navigazione di primo livello ancorata in cima al viewport di un sito o una app.
```

2024-03-07 16:46 UTC, Fupete commented on src/data/content/design-system/componenti/bottomnav.yaml
> +              ![Gli elementi che formano il pulsante](/images/design-system/componenti/bottomnav-anatomy.png)
```suggestion
              ![Gli elementi che formano la Bottomnav](/images/design-system/componenti/bottomnav-anatomy.png)
```

2024-03-07 16:46 UTC, Fupete commented on src/data/content/design-system/componenti/bottomnav.yaml
> +              - Il componente BottomNav rimane fisso a fondo pagina durante lo scroll;
```suggestion
              - Il componente BottomNav rimane fisso a fondo pagina durante lo scroll.
```

2024-03-07 16:47 UTC, Fupete approved these changes

2024-03-07 16:48 UTC, danielenole approved these changes

2024-03-07 16:58 UTC, merged