content(ds): review `back` component
italia/designers.italia.it pull request #1265
Opened 2024-03-05 09:43 UTC by Fupete

2024-03-05 14:30 UTC, danielenole approved these changes

2024-03-05 16:01 UTC, zetareticoli requested changes

2024-03-05 16:01 UTC, zetareticoli commented on src/data/content/design-system/componenti/back.yaml
> +              - **icona**: può essere una freccia verso sinistra per indicare l'azione di navigare alla pagina precedente, la stessa azione compiuta dal Back del browser; o può essere una freccia ver
```suggestion
              1. **icona**: può essere una freccia verso sinistra per indicare l'azione di navigare alla pagina precedente, la stessa azione compiuta dal Back del browser; o può essere una freccia verso l'alto a indicare la navigazione ad un livello gerarchico superiore; 
```

2024-03-05 16:01 UTC, zetareticoli commented on src/data/content/design-system/componenti/back.yaml
> +              - **etichetta** (label): opzionale, rende esplicita l'azione;
```suggestion
              2. **etichetta** (label): opzionale, rende esplicita l'azione; 
```

2024-03-05 16:01 UTC, zetareticoli commented on src/data/content/design-system/componenti/back.yaml
> +              - **forma di sfondo**: presente nel caso delle varianti pulsante.
```suggestion
              3. **forma di sfondo**: presente nel caso delle varianti pulsante. 
```

2024-03-07 16:25 UTC, zetareticoli approved these changes

2024-03-07 16:25 UTC, merged