content(ds): feat new Fondamento `Identità`
italia/designers.italia.it pull request #1290
Opened 2024-03-20 18:28 UTC by Fupete

2024-03-21 11:28 UTC, pedromaria88 requested changes
rivisti i contenuti

2024-03-21 11:28 UTC, pedromaria88 commented on src/data/content/design-system/fondamenti/identita.yaml
> +
non eccederei nella paragrafazione. diventa faticoso da leggere

2024-03-21 11:28 UTC, pedromaria88 commented on src/data/content/design-system/fondamenti/identita.yaml
> +
same, remove?

2024-03-21 11:28 UTC, pedromaria88 commented on src/data/content/design-system/fondamenti/identita.yaml
> +            #### Per essere coerenti ma non uniformi
Per essere aperti e coerenti, non uniformi

2024-03-21 11:28 UTC, pedromaria88 commented on src/data/content/design-system/fondamenti/identita.yaml
> +
Farlo non è solo possibile, ma opportuno e benvenuto: l'identità visiva digitale dello Stato è aperta (open), come deve essere ogni aspetto del digitale pubblico.

2024-03-21 11:35 UTC, pedromaria88 approved these changes

2024-03-22 09:05 UTC, gianvitofanelli commented on src/data/content/design-system/fondamenti.yaml
> +        text: "Armonizzare, coordinare e promuovere un sistema integrato di identità, nello stile e nell'esperienza d'uso, che riguarda i punti di contatto digitali della Pubblica Amministrazione ha
```suggestion
        text: "Armonizzare, coordinare e promuovere un sistema integrato di identità, nello stile e nell'esperienza d'uso, che riguarda i touchpoint digitali della Pubblica Amministrazione ha lo scopo di rendere migliore l’esperienza delle persone su siti e servizi, realizzare prodotti istituzionali facilmente identificabili e aumentare la fiducia nei servizi digitali pubblici attraverso la loro riconoscibilità."
```

2024-03-22 09:06 UTC, gianvitofanelli commented on src/data/content/design-system/fondamenti/identita.yaml
> +            1. **Accessibilità**
```suggestion
            1. **accessibilità;** 
```

2024-03-22 09:06 UTC, gianvitofanelli commented on src/data/content/design-system/fondamenti/identita.yaml
> +            2. **Riconoscibilità e coerenza visiva**
```suggestion
            2. **riconoscibilità e coerenza visiva;** 
```

2024-03-22 09:06 UTC, gianvitofanelli commented on src/data/content/design-system/fondamenti/identita.yaml
> +            3. **Funzionalità minime e coerenza funzionale**
```suggestion
            3. **funzionalità minime e coerenza funzionale.** 
```

2024-03-22 09:06 UTC, gianvitofanelli commented on src/data/content/design-system/fondamenti/identita.yaml
> +            Per l’[accessibilità](/design-system/fondamenti/accessibilita/), è disponibile un fondamento dedicato dove approfondire norme, approccio e strumenti. Gli altri due elementi di coerenza, c
```suggestion
            Per l’[accessibilità](/design-system/fondamenti/accessibilita/), è disponibile un fondamento dedicato nel quale approfondire norme, approccio e strumenti. Gli altri due elementi di coerenza, che costituiscono il fulcro del sistema di identità dell'esperienza dei servizi pubblici italiani, sono descritti di seguito. 
```

2024-03-22 09:07 UTC, gianvitofanelli commented on src/data/content/design-system/fondamenti/identita.yaml
> +            ![](/images/image-icons-fullwidth.jpg)
Non sono sicurissimo dell'immagine fra titolo e indicazioni.

2024-03-22 09:08 UTC, gianvitofanelli commented on src/data/content/design-system/fondamenti/identita.yaml
> +            - usa per il **carattere tipografico (font) principale il Titillium**, ed eventualmente altri caratteri secondari secondo quanto descritto nel fondamento **[Tipografia](/design-system/fon
```suggestion
            - usa **Titillium come carattere tipografico (font) principale**, ed eventualmente altri caratteri secondari secondo quanto descritto nel fondamento **[Tipografia](/design-system/fondamenti/tipografia/)**;
```

2024-03-22 09:08 UTC, gianvitofanelli commented on src/data/content/design-system/fondamenti/identita.yaml
> +            - usa per il **carattere tipografico (font) principale il Titillium**, ed eventualmente altri caratteri secondari secondo quanto descritto nel fondamento **[Tipografia](/design-system/fon
```suggestion
           - usa **Titillium come carattere tipografico (font) principale**, ed eventualmente altri caratteri secondari secondo quanto descritto nel fondamento **[Tipografia](/design-system/fondamenti/tipografia/)**;
```

2024-03-22 09:08 UTC, gianvitofanelli commented on src/data/content/design-system/fondamenti/identita.yaml
> +            - usa per il **carattere tipografico (font) principale il Titillium**, ed eventualmente altri caratteri secondari secondo quanto descritto nel fondamento **[Tipografia](/design-system/fon
```suggestion
            - usa **Titillium come carattere tipografico (font) principale**, ed eventualmente altri caratteri secondari secondo quanto descritto nel fondamento **[Tipografia](/design-system/fondamenti/tipografia/)**;
```

2024-03-22 09:09 UTC, gianvitofanelli commented on src/data/content/design-system/fondamenti/identita.yaml
> +            Per perseguire un'esperienza coerente per i servizi digitali del Paese, e allo stesso tempo garantire una sufficiente differenziazione ad evitare l'uniformità, è possibile agire su:
```suggestion
            Per offrire un'esperienza coerente per i servizi digitali del Paese, e allo stesso tempo garantire una differenziazione sufficiente ad evitare l'uniformità, è possibile agire su: 
```

2024-03-22 09:09 UTC, gianvitofanelli commented on src/data/content/design-system/fondamenti/identita.yaml
> +            - ri-elaborazioni e integrazioni dell'aspetto visivo usando i **colori secondari** (applicabili ad esempio a sfondi, icone, elementi con un peso specifico secondario);
```suggestion
            - ri-elaborazioni e integrazioni dell'aspetto visivo usando i **colori secondari** (applicabili, ad esempio, a sfondi, icone, elementi con un peso specifico secondario); 
```

2024-03-22 09:09 UTC, gianvitofanelli commented on src/data/content/design-system/fondamenti/identita.yaml
> +            - **generazione dinamica di sistemi coordinati di più identità visive** (ad esempio per servizi declinabili su più Regioni, integrando per ognuna elementi della propria identità visiva).
```suggestion
            - **generazione dinamica di sistemi coordinati di più identità visive** (ad esempio ,per servizi declinabili su più Regioni, integrando per ognuna elementi della propria identità visiva). 
```

2024-03-22 09:10 UTC, gianvitofanelli commented on src/data/content/design-system/fondamenti/identita.yaml
> +            Questi indicatori tracciano **la presenza di una serie di funzionalità minime**, necessarie a **garantire la tutela dei diritti digitali delle persone** in relazione ai servizi pubblici.
```suggestion
            Questi indicatori tracciano **la presenza di una serie di funzionalità minime**, necessarie a **garantire la tutela dei diritti digitali delle persone** in relazione ai servizi pubblici. Sebbene queste funzionalità dovrebbero emergere come requisito nelle fasi preliminari del processo di progettazione, è opportuno verificare durante la fase di realizzazione delle interfacce la loro presenza e corretta implementazione. 
```

2024-03-22 09:11 UTC, gianvitofanelli commented on src/data/content/design-system/fondamenti/identita.yaml
> +            - **indicare chiaramente i passi necessari al completamento** della presentazione dell’istanza stessa e l’ottenimento del beneficio atteso, in ogni momento della fruizione dello specifico
```suggestion
            - **indicare chiaramente i passi necessari per completare** la presentazione di un'istanza e ottenere il beneficio atteso, in ogni momento della fruizione dello specifico servizio digitale e fino alla risposta della Pubblica Amministrazione all’istanza; 
```

2024-03-22 09:11 UTC, gianvitofanelli commented on src/data/content/design-system/fondamenti/identita.yaml
> +            - **consente di richiedere assistenza** durante l’utilizzo;
```suggestion
            - **consentire di richiedere assistenza** durante l’utilizzo; 
```

2024-03-22 09:12 UTC, gianvitofanelli commented on src/data/content/design-system/fondamenti/identita.yaml
> +            - **consente di fornire una valutazione**, recensione o feedback del servizio stesso.
```suggestion
            - **consentire di fornire una valutazione**, recensione o feedback del servizio stesso.
```

2024-03-22 09:12 UTC, gianvitofanelli requested changes
Ho lasciato un po' di osservazioni sul testo.

2024-03-22 09:55 UTC, Fupete commented on src/data/content/design-system/fondamenti/identita.yaml
> +           - usa **Titillium come carattere tipografico (font) principale**, ed eventualmente altri caratteri secondari secondo quanto descritto nel fondamento **[Tipografia](/design-system/fondament
```suggestion
            - usa **Titillium come carattere tipografico (font) principale**, ed eventualmente altri caratteri secondari secondo quanto descritto nel fondamento **[Tipografia](/design-system/fondamenti/tipografia/)**;
```

2024-03-22 10:06 UTC, danielenole commented on src/data/content/design-system/fondamenti/identita.yaml
> +            #### Se realizzi servizi digitali **a scala territoriale**:
```suggestion
            #### Servizi digitali **su scala territoriale**
```

2024-03-22 10:06 UTC, danielenole commented on src/data/content/design-system/fondamenti/identita.yaml
> +            - verifica l'esistenza di un **modello di sito o servizio digitale** tra quelli disponibili nella sezione [Modelli](/modelli/);
```suggestion
            Se realizzi servizi digitali su scala territoriale:
            - verifica l'esistenza di un **modello di sito o servizio digitale** tra quelli disponibili nella sezione [Modelli](/modelli/);
```

2024-03-22 10:06 UTC, danielenole commented on src/data/content/design-system/fondamenti/identita.yaml
> +            #### Se realizzi servizi digitali **a scala locale**:
```suggestion
            #### Servizi digitali **su scala locale**
```

2024-03-22 10:07 UTC, danielenole commented on src/data/content/design-system/fondamenti/identita.yaml
> +            - verifica l'esistenza di un **modello di sito o servizio digitale** tra quelli disponibili nella sezione [Modelli](/modelli/);
```suggestion
            Se realizzi servizi digitali su scala locale:
            - verifica l'esistenza di un **modello di sito o servizio digitale** tra quelli disponibili nella sezione [Modelli](/modelli/);
```

2024-03-22 10:13 UTC, danielenole commented on src/data/content/design-system/fondamenti/identita.yaml
> +            Per offrire un'esperienza coerente per i servizi digitali del Paese, e allo stesso tempo garantire una differenziazione sufficiente ad evitare l'uniformità, è possibile agire su:
```suggestion
            Per offrire un'esperienza coerente per i servizi digitali del Paese, e allo stesso tempo garantire una differenziazione sufficiente a evitare l'uniformità, puoi: 
```

2024-03-22 10:16 UTC, danielenole commented on src/data/content/design-system/fondamenti/identita.yaml
> +            - ri-elaborazioni e integrazioni dell'aspetto visivo usando i **colori secondari** (applicabili, ad esempio, a sfondi, icone, elementi con un peso specifico secondario);
```suggestion
            - ri-elaborare e integrare l'aspetto visivo usando i **colori secondari** (applicabili, ad esempio, a sfondi, icone, elementi con un peso specifico secondario); 
```

2024-03-22 10:16 UTC, danielenole commented on src/data/content/design-system/fondamenti/identita.yaml
> +            - uso di **media**, **illustrazioni e motivi grafici**;
```suggestion
            - usare **media**, **illustrazioni** e **motivi grafici**;
```

2024-03-22 10:16 UTC, danielenole commented on src/data/content/design-system/fondamenti/identita.yaml
> +            - uso di **animazioni** e **micro-animazioni**;
```suggestion
            - usare **animazioni** e **micro-animazioni**;
```

2024-03-22 10:17 UTC, danielenole commented on src/data/content/design-system/fondamenti/identita.yaml
> +            - **generazione dinamica di sistemi coordinati di più identità visive** (ad esempio ,per servizi declinabili su più Regioni, integrando per ognuna elementi della propria identità visiva).
```suggestion
            - generare in modo dinamico **sistemi coordinati di più identità visive** (ad esempio, per servizi declinabili su più Regioni, integrando per ognuna elementi della propria identità visiva). 
```

2024-03-22 13:38 UTC, danielenole approved these changes

2024-03-28 11:14 UTC, gianvitofanelli approved these changes

2024-03-29 17:40 UTC, merged