content: how to contribute to UI in Figma
italia/designers.italia.it pull request #1327
Opened 2024-05-14 15:27 UTC by zetareticoli

We changed the contribution process for UI design files in Figma.

2024-05-21 08:45 UTC, danielenole requested changes

2024-05-21 08:45 UTC, danielenole commented on src/data/content/design-system/come-contribuire/per-il-design.yaml
> +              4. **condividi l'indirizzo del file** Figma realizzato, allegandolo alla segnalazione o al commento, impostando i permessi di accesso in sola lettura (view only); in questo modo potremo
```suggestion
              4. **condividi l'indirizzo del file** Figma realizzato, allegandolo alla segnalazione o al commento, impostando i permessi di accesso in sola lettura (view only). In questo modo potremo valutare più velocemente il tuo contributo.
```

2024-05-22 08:37 UTC, danielenole approved these changes

2024-05-24 09:12 UTC, Fupete commented on src/data/content/design-system/come-contribuire/per-il-design.yaml
> +              1. **scarica una copia** della versione più recente di UI Kit Italia disponibile in [Figma Community](https://www.figma.com/community/file/1105848677422572920/ui-kit-italia-v3-4-0);
```suggestion
              1. **copia** nei draft del tuo profilo Figma la versione più recente di UI Kit Italia disponibile in [Figma Community](https://www.figma.com/community/file/1105848677422572920);
```

2024-05-24 09:14 UTC, Fupete approved these changes

2024-05-24 11:52 UTC, merged