docs: `Toolbar` component
italia/designers.italia.it pull request #1368
Opened 2024-07-12 12:50 UTC by zetareticoli

The `toolbar` component page

2024-07-18 14:46 UTC, danielenole requested changes

2024-07-18 14:46 UTC, danielenole commented on src/data/content/design-system/componenti/toolbar.yaml
> +              - Usa il componente `BottomNav` per creare un menu in stile app mobile che sia sempre fissa nella parte inferiore dello schermo.
```suggestion
              - **[BottomNav](/design-system/componenti/bottomnav):** per creare un menu in stile app mobile che sia sempre fissa nella parte inferiore dello schermo.
```

2024-07-18 14:46 UTC, danielenole commented on src/data/content/design-system/componenti/toolbar.yaml
> +              - Usa il componente `Header` per realizzare un menu di navigazione classico.
```suggestion
              - **[Header](/design-system/componenti/header):** per realizzare un menu di navigazione classico.
```

2024-07-18 14:46 UTC, danielenole commented on src/data/content/design-system/componenti/toolbar.yaml
> +              - Usa il componente toolbar insieme ad un elemento di intestazione come ad esempio [slim header](#) per dare un contesto di prodotto.
```suggestion
              - Usa la toolbar insieme a un elemento di intestazione, come ad esempio uno [slim header](#), per dare un contesto di prodotto.
```

2024-07-18 14:46 UTC, danielenole commented on src/data/content/design-system/componenti/toolbar.yaml
> +              - Usa la variante laterale nel caso in cui sia presente un [header](#) completo.
```suggestion
              - Usa la variante laterale nel caso in cui sia presente un [header](/design-system/componenti/header) completo.
```

2024-07-18 14:46 UTC, danielenole commented on src/data/content/design-system/componenti/toolbar.yaml
> +              - Usa i divisori per raggruppare voci di menu che appartengono ad uno stesso gruppo logico.
```suggestion
              - Usa i divisori per raggruppare voci di menu che appartengono a uno stesso gruppo logico.
```

2024-07-18 14:46 UTC, danielenole commented on src/data/content/design-system/componenti/toolbar.yaml
> +              - Scegliere icone con un significato chiaro e che descriva bene i contenuti ad esso associati.
```suggestion
              - Scegliere icone che descrivano in modo chiari i contenuti associati.
```

2024-07-18 14:46 UTC, danielenole commented on src/data/content/design-system/componenti/toolbar.yaml
> +              - Usa una parola singola per l’etichetta associata all’icona.
```suggestion
              - Usa una parola singola e chiara per l’etichetta associata all’icona.
```

2024-07-18 14:46 UTC, danielenole commented on src/data/content/design-system/componenti/toolbar.yaml
> +              Il componente toolbar è composto da:
```suggestion
              Il componente Toolbar è composto da:
```

2024-07-18 14:46 UTC, danielenole commented on src/data/content/design-system/componenti/toolbar.yaml
> +              - Il componente toolbar si adatta alla dimensione del contenitore in larghezza o altezza, a seconda della variante.
```suggestion
              - Il componente Toolbar si adatta alla dimensione del contenitore in larghezza o altezza, a seconda della variante.
```

2024-07-18 14:46 UTC, danielenole commented on src/data/content/design-system/componenti/toolbar.yaml
> +              BottomNav](/images/design-system/componenti/bottomnav-specs.png)
Qui è corretto ci siano le specifiche del bottomnav?

2024-07-18 14:46 UTC, danielenole commented on src/data/content/design-system/componenti/toolbar.yaml
> +              - Usa il componente toolbar insieme ad un elemento di intestazione come ad esempio [slim header](#) per dare un contesto di prodotto.
Qui dove dobbiamo linkare? Alla pagina del componente Header?

2024-07-23 08:29 UTC, zetareticoli commented on src/data/content/design-system/componenti/toolbar.yaml
> +              - Usa il componente toolbar insieme ad un elemento di intestazione come ad esempio [slim header](#) per dare un contesto di prodotto.
sì, possiamo rimandare al componente header

2024-07-23 08:30 UTC, zetareticoli commented on src/data/content/design-system/componenti/toolbar.yaml
> +              - Il componente toolbar si adatta alla dimensione del contenitore in larghezza o altezza, a seconda della variante.
@danielenole non stiamo usando sempre la minuscola per i nomi componenti all'interno di una frase?

2024-07-23 08:31 UTC, zetareticoli commented on src/data/content/design-system/componenti/toolbar.yaml
> +              BottomNav](/images/design-system/componenti/bottomnav-specs.png)
sì, perché coincidono, possiamo modificare l'attributo `alt`

2024-08-06 13:14 UTC, Fupete commented on src/data/content/design-system/componenti/toolbar.yaml
> +              BottomNav](/images/design-system/componenti/bottomnav-specs.png)
```suggestion
              Toolbar](/images/design-system/componenti/bottomnav-specs.png)
```

2024-08-06 13:22 UTC, merged