Update accordion.yaml
italia/designers.italia.it pull request #1384
Opened 2024-08-21 16:10 UTC by danielenole

2024-08-22 16:35 UTC, danielenole commented
@zetareticoli tutto pronto per essere mergiato e deployato!

2024-08-26 09:37 UTC, zetareticoli requested changes

2024-08-26 09:37 UTC, zetareticoli commented on src/data/content/design-system/componenti/rating.yaml
>                Il componente Rating è composto da:
```suggestion
              Il componente rating è composto da:
```

2024-08-26 09:37 UTC, zetareticoli commented on src/data/content/design-system/componenti/select.yaml
>                Per il componente Select aperto si consiglia di utilizzare lo
```suggestion
              Per il componente select aperto si consiglia di utilizzare lo
```

2024-08-26 09:37 UTC, zetareticoli commented on src/data/content/design-system/componenti/sidebar.yaml
>                Il componente Sidebar è composto da:
```suggestion
              Il componente sidebar è composto da:
```

2024-08-26 09:37 UTC, zetareticoli commented on src/data/content/design-system/componenti/skiplinks.yaml
> +              Usa il componente Skiplink ogni volta che all'interno di una
```suggestion
              Usa il componente skiplink ogni volta che all'interno di una
```

2024-08-26 09:37 UTC, zetareticoli commented on src/data/content/design-system/componenti/skiplinks.yaml
> +              È raccomandato l'uso di skiplinks all'inizio di ogni pagina, prima
```suggestion
              È raccomandato l'uso di skiplink all'inizio di ogni pagina, prima
```

2024-08-26 09:37 UTC, zetareticoli commented on src/data/content/design-system/componenti/skiplinks.yaml
>                Un elemento del componente Skiplinks è composto da:
```suggestion
              Un elemento del componente skiplinks è composto da:
```

2024-08-26 09:37 UTC, zetareticoli commented on src/data/content/design-system/componenti/steppers.yaml
> +              Usa il componente Stepper per suddividere i passaggi di una
```suggestion
              Usa il componente stepper per suddividere i passaggi di una
```

2024-08-26 09:37 UTC, zetareticoli commented on src/data/content/design-system/componenti/tabs.yaml
>                del componente Tabs:
```suggestion
              del componente tabs:
```

2024-08-26 09:37 UTC, zetareticoli commented on src/data/content/design-system/componenti/timeline.yaml
>                Usa il componente Timeline quando devi presentare una serie di
```suggestion
              Usa il componente timeline quando devi presentare una serie di
```

2024-08-26 09:37 UTC, zetareticoli commented on src/data/content/design-system/componenti/timeline.yaml
>                Il componente Timeline è composto da:
```suggestion
              Il componente timeline è composto da:
```

2024-08-26 09:37 UTC, zetareticoli commented on src/data/content/design-system/componenti/toggles.yaml
> +              Usa il componente Toggle, nel contesto di un modulo
```suggestion
              Usa il componente toggle, nel contesto di un modulo
```

2024-08-26 09:37 UTC, zetareticoli commented on src/data/content/design-system/componenti/toggles.yaml
> +              Il componente Toggle è composto da:
```suggestion
              Il componente toggle è composto da:
```

2024-08-26 09:37 UTC, zetareticoli commented on src/data/content/design-system/componenti/toolbar.yaml
>                Il componente Toolbar è composto da:
```suggestion
              Il componente toolbar è composto da:
```

2024-08-26 09:37 UTC, zetareticoli commented on src/data/content/design-system/componenti/toolbar.yaml
> +              Il componente Toolbar si adatta alla dimensione del contenitore
```suggestion
              Il componente toolbar si adatta alla dimensione del contenitore
```

2024-08-26 09:37 UTC, zetareticoli commented on src/data/content/design-system/componenti/tooltip.yaml
>                Usa il componente Tooltip quando vuoi fornire ulteriori
```suggestion
              Usa il componente tooltip quando vuoi fornire ulteriori
```

2024-08-26 09:37 UTC, zetareticoli commented on src/data/content/design-system/componenti/tooltip.yaml
>                 Il componente Tooltip è composto da:
```suggestion
               Il componente tooltip è composto da:
```

2024-08-27 14:03 UTC, danielenole commented on src/data/content/design-system/componenti/bottomnav.yaml
>                Il componente BottomNav è composto da:
cambio in bottomnav

2024-08-27 14:36 UTC, zetareticoli approved these changes

2024-08-28 14:56 UTC, Fupete requested changes
Finirei di correggere i formati Maiuscolo/minuscolo prima di mergiare.

2024-08-28 14:59 UTC, Fupete commented on src/data/content/design-system/componenti/avatar.yaml
> +              - Indicare una sola persona con ogni Avatar.
```suggestion
              - Indicare una sola persona con ogni avatar.
```

2024-08-28 14:59 UTC, Fupete commented on src/data/content/design-system/componenti/avatar.yaml
> +              Le varianti del componente Avatar possono essere composte con i
```suggestion
              Le varianti del componente avatar possono essere composte con i
```

2024-08-28 14:59 UTC, Fupete commented on src/data/content/design-system/componenti/avatar.yaml
> +              Le varianti lista (o gruppo) del componente Avatar possono essere
```suggestion
              Le varianti lista (o gruppo) del componente avatar possono essere
```

2024-08-28 15:01 UTC, danielenole commented on src/data/content/design-system/componenti/forward.yaml
>                - Usa un componente Forward nel contesto di pagine lunghe con
```suggestion
              - Usa un componente forward nel contesto di pagine lunghe con
```

2024-08-28 15:01 UTC, danielenole commented on src/data/content/design-system/componenti/forward.yaml
>                Il componente Forward è composto da:
```suggestion
              Il componente forward è composto da: 
```

2024-08-28 15:04 UTC, Fupete commented on src/data/content/design-system/componenti/accordion.yaml
> +              [Collapse](/design-system/componenti/collapse/).
```suggestion
              [collapse](/design-system/componenti/collapse/).
```

2024-08-28 15:05 UTC, Fupete commented on src/data/content/design-system/componenti/alert.yaml
> +              Alert](/images/design-system/componenti/alert-anatomy.png)
```suggestion
              alert](/images/design-system/componenti/alert-anatomy.png)
```

2024-08-28 15:05 UTC, Fupete commented on src/data/content/design-system/componenti/alert.yaml
> +              Alert](/images/design-system/componenti/alert-specs-1.png)
```suggestion
              alert](/images/design-system/componenti/alert-specs-1.png)
```

2024-08-28 15:05 UTC, Fupete commented on src/data/content/design-system/componenti/alert.yaml
> +              Alert](/images/design-system/componenti/alert-specs-2.png)
```suggestion
              alert](/images/design-system/componenti/alert-specs-2.png)
```

2024-08-28 15:05 UTC, Fupete commented on src/data/content/design-system/componenti/alert.yaml
> +              Alert](/images/design-system/componenti/alert-specs-3.png)
```suggestion
              alert](/images/design-system/componenti/alert-specs-3.png)
```

2024-08-28 15:06 UTC, Fupete commented on src/data/content/design-system/componenti/back.yaml
> +              [Button](/design-system/componenti/buttons/) composta da:
```suggestion
              [button](/design-system/componenti/buttons/) composta da:
```

2024-08-28 15:06 UTC, Fupete commented on src/data/content/design-system/componenti/back.yaml
> +              [Button](/design-system/componenti/buttons/).
```suggestion
              [button](/design-system/componenti/buttons/).
```

2024-08-28 15:06 UTC, Fupete commented on src/data/content/design-system/componenti/back.yaml
> +              [Button](/design-system/componenti/buttons/).
```suggestion
              [button](/design-system/componenti/buttons/).
```

2024-08-28 15:08 UTC, Fupete commented on src/data/content/design-system/componenti/modal.yaml
> +              **[Popover](/design-system/componenti/popover)**: per spiegare una
```suggestion
              **[popover](/design-system/componenti/popover)**: per spiegare una
```

2024-08-28 15:11 UTC, Fupete approved these changes

2024-08-29 07:37 UTC, merged