content(feat): launch design system v1 news event and media
italia/designers.italia.it pull request #1429
Opened 2024-10-11 09:29 UTC by Fupete

2024-10-21 15:38 UTC, danielenole requested changes

2024-10-21 15:38 UTC, danielenole commented on src/data/content/community/notizie/20241021-italia-versione-1.yaml
> +            **Ad oggi .italia fa già la differenza**: nell’ultimo anno più di 9000 persone al mese hanno visitato la sezione dedicata al design system sul sito di Designers Italia e più di 10000 pubb
```suggestion
            **Ad oggi .italia fa già la differenza**: nell’ultimo anno più di 9000 persone al mese hanno visitato la sezione dedicata al design system sul sito di Designers Italia e più di 10.000 pubbliche amministrazioni l’hanno usato per erogare, alla cittadinanza, servizi digitali accessibili, usabili e coerenti.
```

2024-10-21 15:38 UTC, danielenole commented on src/data/content/community/notizie/20241021-italia-versione-1.yaml
> +            Il rilascio della versione 1 del design system .italia include una **libreria ricca di componenti già testati in termini di usabilità e accessibilità**, **documentazione completa** per ci
```suggestion
            Il rilascio della versione 1 del design system .italia include una **libreria ricca di componenti già testati in termini di usabilità e accessibilità**, **documentazione completa** per ciascun componente e **framework moderni per sviluppare** in modo rapido ed efficace.
```

2024-10-21 15:38 UTC, danielenole commented on src/data/content/community/notizie/20241021-italia-versione-1.yaml
> +            **L’accessibilità si conferma quindi una priorità del design system** e uno dei tre pilastri dell’identità dei servizi pubblici digitali ([Fondamento Identità](/design-system/fondamenti/i
```suggestion
            **L’accessibilità si conferma quindi una priorità del design system** e [uno dei tre pilastri dell’identità dei servizi pubblici digitali](/design-system/fondamenti/identita/). In un’ottica di miglioramento continuo e per garantire la massima qualità e affidabilità del sistema, abbiamo svolto ben tre cicli di verifiche di accessibilità e coerenza sui 55 componenti, seguendo un workflow definito nel tempo insieme agli esperti di accessibilità di AgID. Abbiamo inoltre messo a disposizione di tutti [questo processo di verifica](/design-system/fondamenti/accessibilita/), così che le PA e i loro fornitori possano replicarlo per verificare l’accessibilità dei componenti nel contesto dei siti e servizi digitali che stanno sviluppando.
```

2024-10-21 15:38 UTC, danielenole commented on src/data/content/community/notizie/20241021-italia-versione-1.yaml
> +            Il rilascio ufficiale della versione 1 chiude la [fase beta](/community/notizie/20240308-ciao-italia-la-terza-generazione-del-design-system-ha-un-nome-ed-entra-in-fase-beta/) iniziata a m
```suggestion
            Il rilascio ufficiale della versione 1 chiude la [fase beta](/community/notizie/20240308-ciao-italia-la-terza-generazione-del-design-system-ha-un-nome-ed-entra-in-fase-beta/) iniziata a marzo 2024 e **consolida due anni e mezzo di progettazione e sviluppo in cui abbiamo rilasciato [oltre 25 versioni](/design-system/fondamenti/versionamento/#changelog-documentazione)**, dalla prima `v1.0.0-alpha.1` all’attuale `v1.1.0`. Questo lavoro non sarebbe stato possibile senza la collaborazione della community di Designers Italia e Developers Italia, che supporta l’evoluzione di .italia sin dalla sua nascita, tenendo il progetto vivo e in continuo miglioramento.
```

2024-10-21 15:38 UTC, danielenole commented on src/data/content/community.yaml
> +      - title: "Design system .italia"
```suggestion
      - title: "Design system .italia: uno strumento di valore per PA e cittadinanza"
```

2024-10-21 15:38 UTC, danielenole commented on src/data/content/community/media/20241021-design-system-italia.yaml
> +  name: "ll design system .italia: uno strumento di valore per PA e cittadinanza"
```suggestion
  name: "Design system .italia: uno strumento di valore per PA e cittadinanza"
```

2024-10-21 15:38 UTC, danielenole commented on src/data/content/community/media/20241021-design-system-italia.yaml
> +    title: "ll design system .italia: uno strumento di valore per PA e cittadinanza"
```suggestion
    title: "Design system .italia: uno strumento di valore per PA e cittadinanza"
```

2024-10-21 15:59 UTC, astagi approved these changes

2024-10-21 16:10 UTC, Fupete commented on src/data/content/community/notizie/20241021-italia-versione-1.yaml
> +            **Ad oggi .italia fa già la differenza**: nell’ultimo anno più di 9000 persone al mese hanno visitato la sezione dedicata al design system sul sito di Designers Italia e più di 10.000 pub
```suggestion
            **Ad oggi .italia fa già la differenza**: nell’ultimo anno più di 9.000 persone al mese hanno visitato la sezione dedicata al design system sul sito di Designers Italia e più di 10.000 pubbliche amministrazioni l’hanno usato per erogare, alla cittadinanza, servizi digitali accessibili, usabili e coerenti.
```

2024-10-22 12:59 UTC, danielenole approved these changes

2024-10-22 13:05 UTC, merged