chore: add Docker development environment
italia/designers.italia.it pull request #249
Opened 2021-12-18 12:03 UTC by bfabio

2021-12-20 08:23 UTC, libremente requested changes
Thanks @bfabio! Please also add a line in the README with the localhost:4000 indication :)

2021-12-20 08:23 UTC, libremente commented on README.md
> +1. Esegui l'ambiente di sviluppo
```suggestion
2. Esegui l'ambiente di sviluppo
```

2021-12-20 10:11 UTC, bfabio commented
> Thanks @bfabio! Please also add a line in the README with the localhost:4000 indication :)

Right, good catch!

2021-12-21 12:46 UTC, libremente approved these changes
LGTM! :rocket:

2021-12-21 16:14 UTC, merged