feat: new fondamenti pages + table styling
italia/designers.italia.it pull request #759
Opened 2023-05-05 07:03 UTC by Fupete

Moved to release alpha.5 cc @danielaiozzo @danielenole

2023-05-05 15:44 UTC, Fupete commented
@astagi it seems to me that we just need to merge/complete this PR on BSI https://github.com/italia/bootstrap-italia/pull/890 before merging this. Or, maybe just the last example in the `json` still looks weird, I don't think it found the JS function to upload the YouTube video. Let's talk about this on Wednesday.

2023-05-08 14:47 UTC, danielaiozzo requested changes
@Fupete some missed quotation marks in some CTA cc @bfabio

2023-05-08 14:47 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/microtesti.yaml
> +          - label: "Scopri il fondamento dedicato al Tono di voce”" #C
one missed quotation mark

 - label: "Scopri il fondamento dedicato al "Tono di voce”"

2023-05-08 14:47 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/microtesti.yaml
> +          - label: "Scopri il fondamento dedicato al Linguaggio”" #C
one missed quotation mark

label: "Scopri il fondamento dedicato al "Linguaggio”"

2023-05-10 09:23 UTC, danielaiozzo approved these changes

2023-05-10 09:36 UTC, merged