Feat/News "Fondamenti linguaggio"
italia/designers.italia.it pull request #809
Opened 2023-05-24 15:10 UTC by gianvitofanelli

2023-05-24 15:41 UTC, danielaiozzo requested changes

2023-05-24 15:41 UTC, danielaiozzo commented on src/data/content/community/notizie/20230530-design-system-pubblicati-i-fondamenti-di-scrittura-per-l-esperienza-utente.yaml
> +      tags: [Design system, Scrittura, Linguaggio. Microtesti]
```suggestion
      tags: [Design system, Scrittura, Linguaggio, Microtesti]
```

2023-05-24 15:41 UTC, danielaiozzo commented on src/data/content/community/notizie/20230530-design-system-pubblicati-i-fondamenti-di-scrittura-per-l-esperienza-utente.yaml
> +      tags: [Design system, Scrittura, Linguaggio. Microtesti]
@gianvitofanelli probably a comma is needed instead, see preview

2023-05-25 07:52 UTC, danielaiozzo submitted a review, later dismissed
after these changes is ready for merge in my opinion

2023-05-25 07:52 UTC, danielaiozzo commented on src/data/content/community/notizie/20230530-design-system-pubblicati-i-fondamenti-di-scrittura-per-l-esperienza-utente.yaml
> +          - label: Vai ai fondamenti di linguaggio
```suggestion
          - label: Vai al fondamento Linguaggio
```

2023-05-25 07:52 UTC, danielaiozzo commented on src/data/content/community/notizie/20230530-design-system-pubblicati-i-fondamenti-di-scrittura-per-l-esperienza-utente.yaml
> +            Da oggi, il design system si arricchisce di tre nuovi fondamenti dedicati alla **scrittura di contenuti per l’esperienza utente.** Il modo in cui scriviamo, infatti, può migliorare radica
to avoid a repetition

2023-05-25 08:09 UTC, gianvitofanelli commented
@Fupete, how can we show the three final CTAs one above the other?

2023-05-30 13:14 UTC, bfabio approved these changes

2023-05-30 13:15 UTC, merged