content: new contribution model
italia/designers.italia.it pull request #870
Opened 2023-09-05 09:05 UTC by Fupete

2023-09-12 13:05 UTC, Fupete commented on src/data/content/design-system/come-contribuire/modello-di-contribuzione.yaml
> +      "Prendi parte all’evoluzione del design system dedicato alla PA italiana: contribuisci alle discussioni, agli avanzamenti tecnici e di design e scopri come proporre novità e nuove idee da condi
Per usare il markdown andando a capo al rigo prima manca un ` | ` prima del ritorno a capo. Le `"` non servono. Dovrebbe essere `text: | `. 

Sennò puoi metterlo di seguito ai `:` e van bene le `"`. 

@danielaiozzo 🔝

2023-09-13 16:26 UTC, Fupete commented
Ancora da fare:

- [ ] Aggiungere o fare revisione di tutti i contenuti marcati `XXX`
- [ ] Rivedere il linguaggio
- [ ] Schema modello di contribuzione
- [ ] Valutare link a tabella unica segnalazioni da tutte le repository poi filtrabile (tema complicazione gestione aggiunta tag progetto)

2023-09-14 15:49 UTC, danielaiozzo requested changes
some copy suggestions added

2023-09-14 15:49 UTC, danielaiozzo commented on src/data/content/design-system/come-contribuire.yaml
> +  description: Scopri i passi da compiere per contribuire al design system del Paese
```suggestion
  description: Scopri i passi da seguire per contribuire al design system del Paese
```

2023-09-14 15:49 UTC, danielaiozzo commented on src/data/content/design-system/come-contribuire/modello-di-contribuzione.yaml
> +            Il design system del Paese è per tutte le persone, e ognuno può offrire un contributo basato su dati, ricerca utente e test sul campo.
```suggestion
            Il design system del Paese è per tutte le persone, e ogni persona della community può offrire un contributo basato su dati, ricerca utente e test sul campo.
```

2023-09-14 15:49 UTC, danielaiozzo commented on src/data/content/design-system/come-contribuire/modello-di-contribuzione.yaml
> +            Dalla segnalazione di una correzione alla proposta di un’integrazione, dalla presentazione di un nuovo componente alla partecipazione a discussioni su modifiche futuribili, ogni contribut
```suggestion
            Dalla segnalazione di una correzione alla proposta di un’integrazione, dalla presentazione di un nuovo componente alla partecipazione a discussioni su modifiche futuribili, come contributor puoi prendere parte al miglioramento continuo del progetto e alla realizzazione di siti e servizi digitali della PA sempre migliori.
```

2023-09-14 15:49 UTC, danielaiozzo commented on src/data/content/design-system/come-contribuire/modello-di-contribuzione.yaml
> +              1. Potete trovare nelle discussioni la lingua inglese, considerata lingua franca dei progetti open source di design e sviluppo, non vi spaventate non siamo dogmatici
```suggestion
              1. Puoi trovare frequentemente discussioni in lingua inglese perché considerata lingua franca dei progetti open source, in particolare per i temi di design e sviluppo
```

2023-09-14 15:49 UTC, danielaiozzo commented on src/data/content/design-system/come-contribuire/modello-di-contribuzione.yaml
> +              2. Anzi, ci prendiamo l'impegno d'ora in poi di usare l'italiano laddove le discussioni siano inerenti documentazione e contenuti
```suggestion
              2. Laddove le discussioni siano inerenti alla documentazione e ai contenuti, ci sembra però ragionevole usare la lingua italiana per le contribuzioni
```

2023-09-14 15:49 UTC, danielaiozzo commented on src/data/content/design-system/come-contribuire/modello-di-contribuzione.yaml
> +              3. Sono ovviamente benvenuti contributi sia in italiano che inglese
```suggestion
              3. Sono ovviamente benvenuti in maniera paritetica contributi in italiano e in inglese
```

2023-09-14 15:49 UTC, danielaiozzo commented on src/data/content/design-system/come-contribuire/per-il-design.yaml
> +            Se il tema di tuo interesse non è nella lista puoi proporre una nuova segnalazione. Ricorda di inserire tutti i dettagli che ritieni necessari per approfondire il tema, in modo da consent
```suggestion
            Se il tema di tuo interesse non è nella lista puoi proporre una nuova segnalazione. Ricorda di inserire tutti i dettagli che ritieni necessari per approfondire il tema, in modo da consentire alla community e al team di Designers Italia di avere un quadro chiaro e il più possibile completo della tua proposta.    
```

2023-09-14 15:49 UTC, danielaiozzo commented on src/data/content/design-system/come-contribuire/per-la-documentazione.yaml
> +            Se il tema di tuo interesse non è presente nella lista puoi proporre una nuova segnalazione. Ricorda di inserire nella nuova segnalazione tutti i dettagli che ritieni necessari per approf
```suggestion
            Se il tema di tuo interesse non è presente nella lista puoi proporre una nuova segnalazione. Ricorda di inserire nella nuova segnalazione tutti i dettagli che ritieni necessari per approfondire il tema, in modo da consentire alla community e al team di Designers Italia di avere un quadro chiaro e il più possibile completo della tua proposta.   
```

2023-09-14 15:49 UTC, danielaiozzo commented on src/data/content/design-system/come-contribuire/per-lo-sviluppo.yaml
> +            Puoi partecipare a discussioni, aprire segnalazioni e inviare contributi alla principale risorsa di sviluppo. **Bootstrap Italia**. È inoltre possibile collaborare al lavoro di integrazio
```suggestion
            Puoi partecipare a discussioni, aprire segnalazioni e inviare contributi alla principale risorsa di sviluppo **Bootstrap Italia**. È inoltre possibile collaborare al lavoro di integrazione di **Design Tokens Italia** e partecipare all'evoluzione community-driven dei framework React e Angular che implementano Bootstrap Italia.
```

2023-09-14 15:49 UTC, danielaiozzo commented on src/data/content/design-system/come-contribuire/per-lo-sviluppo.yaml
> +            Se il tema di tuo interesse non è nella lista puoi proporre una nuova segnalazione. Ricorda di inserire tutti i dettagli che ritieni necessari ad approfondire.
```suggestion
            Se il tema di tuo interesse non è nella lista puoi proporre una nuova segnalazione. Ricorda di inserire tutti i dettagli che ritieni necessari per approfondire il tuo contributo. 
```

2023-09-15 12:12 UTC, danielaiozzo submitted a review, later dismissed

2023-09-15 12:12 UTC, danielaiozzo commented on src/data/content/design-system/come-contribuire/per-lo-sviluppo.yaml
> +            I lavori in corso per l'aggiornamento a Bootstrap Italia v2 si possono seguire sul ramo [next](https://github.com/italia/design-react-kit/tree/next) della repository e nella [pull request
```suggestion
            Puoi seguire i lavori in corso per l'aggiornamento a Bootstrap Italia v2 sul ramo [next](https://github.com/italia/design-react-kit/tree/next) della repository e nella [pull request (885)](https://github.com/italia/design-react-kit/pull/885) dedicata. 
```

2023-09-15 12:12 UTC, danielaiozzo commented on src/data/content/design-system/come-contribuire/per-lo-sviluppo.yaml
> +       Partecipa all'aggiornamento per renderle coerenti Bootstrap Italia e UI Kit Italia.
```suggestion
       Partecipa all'aggiornamento per rendere coerenti Bootstrap Italia e UI Kit Italia. 
```

2023-09-15 12:12 UTC, danielaiozzo commented on src/data/content/design-system/come-contribuire/per-lo-sviluppo.yaml
> +            I lavori in corso per l'aggiornamento a Bootstrap Italia v2 si possono seguire sulla [repository](https://github.com/italia/design-angular-kit/) e nella [milestone](https://github.com/ita
```suggestion
            Puoi seguire i lavori in corso per l'aggiornamento a Bootstrap Italia v2 sulla [repository](https://github.com/italia/design-angular-kit/) e nella [milestone](https://github.com/italia/design-angular-kit/milestone/3) dedicata.
```

2023-09-15 12:12 UTC, danielaiozzo commented on src/data/content/design-system/come-contribuire/per-lo-sviluppo.yaml
> +            Di seguito trovi informazioni su dove trovare i lavori in corso.
```suggestion
            Di seguito le informazioni su dove trovare i lavori in corso.              
```

2023-09-15 12:12 UTC, danielaiozzo commented on src/data/content/design-system/come-contribuire/per-lo-sviluppo.yaml
> +            Commenti e contributi di tutta la community sono più che necessari!
```suggestion
            I commenti e i contributi di tutta la community sono più che necessari!
```

2023-09-15 12:12 UTC, danielaiozzo commented on src/data/content/design-system/come-contribuire/per-il-design.yaml
> +              Puoi inviare un contributo diretto a Design Tokens Italia proponendo cambi, correzioni o integrazioni ai Tokens disponibili:
```suggestion
              Puoi inviare un contributo diretto a Design Tokens Italia proponendo modifiche, correzioni o integrazioni ai Tokens disponibili:
```

2023-09-15 12:12 UTC, danielaiozzo commented on src/data/content/design-system/come-contribuire/per-il-design.yaml
> +              Nelle lavorazioni poni particolare attenzione al rispetto dei fondamenti del design system del Paese e durante l'editing poni attenzione alla gerarchia dei contenuti nel file, la natura
```suggestion
              Nelle lavorazioni poni particolare attenzione al rispetto dei fondamenti del design system del Paese e durante l'editing poni attenzione alla gerarchia dei contenuti nel file, poiché la natura del formato file è particolarmente sensibile alla corretta indentazione. 
```

2023-09-18 08:51 UTC, danielaiozzo approved these changes

2023-09-18 09:05 UTC, astagi approved these changes

2023-09-18 09:25 UTC, merged