content: added typography content
italia/designers.italia.it pull request #882
Opened 2023-09-15 16:32 UTC by zetareticoli

Added first draft of `Tipografia` page.

In the typography styles tables we need to format text with proper CSS style. 

Example:
"Intestazione 1" should be displayed as a `h1` tag. 

We should investigate how to use html tags inside a table.

2023-09-26 07:27 UTC, danielaiozzo requested changes
@zetareticoli content review done, minor suggestions

2023-09-26 07:27 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/tipografia.yaml
> +  description: "Progetta contenuti chiari, inclusivi, efficaci e pensati per andare incontro alle esigenze delle persone"
```suggestion
  description: "I caratteri, gli stili e le regole tipografiche da usare per presentare i contenuti di un'interfaccia digitale in modo chiaro, leggibile ed efficace"
```

2023-09-26 07:27 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/tipografia.yaml
> +    subtitle: "I caratteri, stili e regole tipografiche utilizzati per presentare i contenuti di un interfaccia utente digitale nel modo più chiaro ed efficace possibile."
```suggestion
    subtitle: "I caratteri, gli stili e le regole tipografiche da usare per presentare i contenuti di un'interfaccia digitale in modo chiaro, leggibile ed efficace"
```

2023-09-26 07:27 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/tipografia.yaml
> +            È possibile utilizzare tre diversi caratteri tipografici, ognuno con un ruolo specifico:
```suggestion
            Nell'ambito di questo design system puoi utilizzare tre diversi caratteri tipografici, ognuno dei quali ha un caso d'uso raccomandato specifico:
```

2023-09-26 07:27 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/tipografia.yaml
> +            Roboto Mono, variante monospaziata della famiglia Roboto, è un carattere ideato per la **visualizzazione di dati tecnici**. La sua uniformità dei caratteri è utile per la rappresentazione
```suggestion
            Roboto Mono, variante monospaziata della famiglia Roboto, è un carattere ideato per la **visualizzazione di dati tecnici**. La sua uniformità dei caratteri è utile per rappresentare numeri, codici, calcoli matematici, e fornire esempi di stringhe di linguaggi di programmazione.
```

2023-09-26 07:27 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/tipografia.yaml
> +            Lora è il carattere tipografico nato espressamente per la **lettura dei testi** su dispostivi digitali. Essendo un font con le grazie (*serif*), è raccomandato per lunghi paragrafi di tes
```suggestion
            Lora è il carattere tipografico nato espressamente per la **lettura dei testi** su dispostivi digitali. Essendo un font con le grazie (*serif*), è raccomandato per paragrafi di testo più lunghi.
```

2023-09-26 07:27 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/tipografia.yaml
> +                La lista di tutti gli stili per il corpo del testo:
```suggestion
                La lista di tutti gli stili per il corpo del testo di una pagina:
```

2023-09-26 07:27 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/tipografia.yaml
> +            Mantieni i paragrafi di testo a una lunghezza ragionevole per migliorare la leggibilità, evitando blocchi di testo troppo lunghi.
```suggestion
            Per una migliore leggibilità dei contenuti ti consigliamo di mantenere i paragrafi di testo entro una lunghezza ragionevole, evitando blocchi di testo troppo lunghi. 
```

2023-09-26 07:27 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/tipografia.yaml
> +            È raccomandata una lunghezza massima di **75-80 caratteri per riga**.
```suggestion
            Raccomandiamo ad esempio una lunghezza massima di **75-80 caratteri per riga**.
```

2023-09-26 07:27 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/tipografia.yaml
> +            La linea di base è di **4px** (*baseline*). Lo spazio occupato da un elemento testuale o tra elementi diversi è un  multiplo di questo valore.
```suggestion
            La linea di base è di **4px** (*baseline*). Lo spazio occupato da un elemento testuale o tra elementi diversi è un multiplo di questo valore.
```

2023-09-26 07:27 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/tipografia.yaml
> +            È consigliabile **non superare quattro livelli di intestazione** (H1, H2, H3 e H4) per pagina, facendo attenzione a definire l’importanza di ciascuna sezione.
```suggestion
            Ti consigliamo di **non superare quattro livelli di intestazione** (H1, H2, H3 e H4) per pagina, facendo attenzione a definire l’importanza di ciascuna sezione.       
```

2023-10-06 15:26 UTC, danielaiozzo requested changes
perfetto

2023-10-06 15:26 UTC, danielaiozzo commented on src/data/content/design-system/fondamenti/tipografia.yaml
> +              Lora è il carattere tipografico nato espressamente per la **lettura dei testi** su dispostivi digitali. Essendo un font con le grazie (*serif*), è raccomandato per paragrafi di testo pi
```suggestion
              Lora è il carattere tipografico nato espressamente per facilitare la **lettura dei testi** su dispostivi digitali. Essendo un font con le grazie (*serif*), è raccomandato per paragrafi di testo più lunghi.
```

2023-10-12 09:20 UTC, Fupete commented on src/data/content/design-system/fondamenti/tipografia.yaml
> +            - Intestazioni (*headings*)
```suggestion
            - Intestazioni (headings)
```

2023-10-12 09:20 UTC, Fupete commented on src/data/content/design-system/fondamenti/tipografia.yaml
> +            - Corpo del testo (*body*)
```suggestion
            - Corpo del testo (body)
```

2023-10-12 09:20 UTC, Fupete commented on src/data/content/design-system/fondamenti/tipografia.yaml
> +            - Etichette e didascalie (*label*, *caption*)
```suggestion
            - Etichette e didascalie (label, caption)
```

2023-10-12 09:21 UTC, Fupete commented on src/data/content/design-system/fondamenti/tipografia.yaml
> +            Lo stile **_lead text_** è raccomandato per creare il sommario di una pagina o sezione.
```suggestion
            Lo stile **lead text** è raccomandato per creare il sommario di una pagina o sezione.
```

2023-10-12 09:21 UTC, Fupete commented on src/data/content/design-system/fondamenti/tipografia.yaml
> +            Lo stile **_label_** può essere utilizzato per elementi testuali composti da una o due parole, come ad esempio le etichette di un _form_.
```suggestion
            Lo stile **label** può essere utilizzato per elementi testuali composti da una o due parole, come ad esempio le etichette di un form.
```

2023-10-12 09:22 UTC, Fupete commented on src/data/content/design-system/fondamenti/tipografia.yaml
> +            Lo stile **_caption_** è dedicato a tutti questi microtesti come didascalie o messaggi di supporto che non necessitano un'attenzione primaria.
```suggestion
            Lo stile **caption** è dedicato a tutti questi microtesti come didascalie o messaggi di supporto che non necessitano un'attenzione primaria.
```

2023-10-12 09:22 UTC, Fupete commented on src/data/content/design-system/fondamenti/tipografia.yaml
> +            Raccomandiamo ad esempio una lunghezza massima di **75-80 caratteri per riga**.
```suggestion
            Raccomandiamo una lunghezza massima di **75 caratteri per riga**.
```

2023-10-12 09:23 UTC, Fupete commented on src/data/content/design-system/fondamenti/tipografia.yaml
> +            Il ritmo verticale è lo spazio occupato dalle lettere su ogni riga di testo e lo spazio tra le righe (*leading*).
```suggestion
            Il ritmo verticale è lo spazio occupato dalle lettere su ogni riga di testo e lo spazio tra le righe (leading). 
```

2023-10-12 09:23 UTC, Fupete commented on src/data/content/design-system/fondamenti/tipografia.yaml
> +            La linea di base è di **4px** (*baseline*). Lo spazio occupato da un elemento testuale o tra elementi diversi è un multiplo di questo valore.
```suggestion
            La linea di base è di **4px** (baseline). Lo spazio occupato da un elemento testuale o tra elementi diversi è un multiplo di questo valore.
```

2023-10-12 09:25 UTC, Fupete reviewed
Fatto salvo le indicazioni sopra — più che altro ho tolto gli italici sulle parole inglesi tecniche, come da regole tipografiche decise per il resto del sito — per me è ok. 
Lascio a @danielaiozzo per revisione finale e approvazione. 

Grazie mille @zetareticoli ottimo lavoro.

2023-10-12 10:20 UTC, danielaiozzo approved these changes

2023-10-13 06:04 UTC, merged