content: added first draft of header doc #893
italia/designers.italia.it pull request #894
Opened 2023-09-22 13:00 UTC by zetareticoli

I created a content draft for the header component.

We need to understand what data is needed for design specifications, considering that the variants differ greatly.

Related to #893 and #876

2023-10-06 15:06 UTC, Fupete requested changes

2023-10-06 15:06 UTC, Fupete commented on src/data/content/design-system/componenti/header.yaml
> +              Lo _slim header_ è una versione più **compatta** e **flessibile** dell’header completa.
Forse va riformulata la frase. 
@zetareticoli @danielaiozzo Lo slim header è più un pezzo possibile dell'header completa che un'alternativa però. È nato e di solito è sempre stato usato per indicare l'ente di appartenenza del progetto o della pagina, oppure l'ente superiore in gerarchia. Vedi il ns uso su Designers per es. Così come le Regioni nel tema Comuni. O il MUR nel tema scuole.

2023-10-06 15:06 UTC, Fupete commented on src/data/content/design-system/componenti/header.yaml
> +              I link del menu di navigazione che prevedono un sottomenu espandibile ereditano le interazioni del componente [dropdown](#).
Link da inserire: `/design-system/componenti/dropdown/`

2023-10-06 15:06 UTC, Fupete commented on src/data/content/design-system/componenti/header.yaml
> +              tramite l’apertura di una finestra (_overlay_) rimanendo nella stessa pagina .
C'è un problema di impaginazione in questo elenco. La seconda riga manca del trattino `-` iniziale.

2023-10-06 15:30 UTC, danielaiozzo commented on src/data/content/design-system/componenti/header.yaml
> +              Lo _slim header_ è una versione più **compatta** e **flessibile** dell’header completa.
```suggestion
              Lo _slim header_ è una porzione dell'header più **compatta** e **flessibile** che può indicare l'appartenenza del sito o servizio a una categoria o a un ordine gerarchico.  
```

2023-10-12 09:13 UTC, Fupete commented on src/data/content/design-system/componenti/header.yaml
> +              Lo _slim header_ è una versione più **compatta** e **flessibile** dell’header completa.
Ok per me.

2023-10-12 09:13 UTC, Fupete commented on src/data/content/design-system/componenti/header.yaml
> +              È necessario utilizzare il componente *header* in cima ad ogni pagina di un sito o servizio digitale della pubblica amministrazione italiana.
```suggestion
              È necessario utilizzare il componente *header* all'inizio di ogni pagina di un sito o servizio digitale della pubblica amministrazione italiana.
```

2023-10-12 09:15 UTC, Fupete commented on src/data/content/design-system/componenti/header.yaml
> +              A differenza della variante “slim header”, l’header centrale preserva il brand garantedo una maggiore visibilità.
```suggestion
```

2023-10-12 09:16 UTC, Fupete commented on src/data/content/design-system/componenti/header.yaml
> +              I link del menu di navigazione che prevedono un sottomenu espandibile ereditano le interazioni del componente [dropdown](#).
```suggestion
              I link del menu di navigazione che prevedono un sottomenu espandibile ereditano le interazioni del componente [dropdown](/design-system/componenti/dropdown/).
```

2023-10-12 09:16 UTC, Fupete commented on src/data/content/design-system/componenti/header.yaml
> +              tramite l’apertura di una finestra (_overlay_) rimanendo nella stessa pagina .
```suggestion
              tramite l’apertura di una finestra (overlay) rimanendo nella stessa pagina .
```

2023-10-12 09:18 UTC, Fupete reviewed
Fatto salvo le indicazioni sopra per me è ok. 
Lascio a @danielaiozzo la revisione finale per approvazione. 

Grazie @zetareticoli.

2023-10-12 10:39 UTC, danielaiozzo requested changes

2023-10-12 10:39 UTC, danielaiozzo commented on src/data/content/design-system/componenti/header.yaml
> +              È necessario utilizzare il componente *header* in cima ad ogni pagina di un sito o servizio digitale della pubblica amministrazione italiana.
```suggestion
              È necessario utilizzare il componente header in cima ad ogni pagina di un sito o servizio digitale della pubblica amministrazione italiana.
```

2023-10-12 10:39 UTC, danielaiozzo commented on src/data/content/design-system/componenti/header.yaml
> +              A differenza della variante “slim header”, l’header centrale preserva il brand garantedo una maggiore visibilità.
```suggestion
              A differenza della variante “slim header”, l’header centrale preserva il brand garantendo una maggiore visibilità.
```

2023-10-12 10:58 UTC, Fupete commented
Riporto in draft (e in lavorazione) solo come promemoria che mancano ancora i contenuti della tab progettazione @zetareticoli @danielaiozzo

2023-10-12 11:27 UTC, Fupete commented
@zetareticoli ti ho generato immagini anatomie e specs, rieditando a mano i risultati del plugin per sintesi. Li trovi su Figma insieme a un po' di commenti. 

![anteprima anatomie e specs header desktop](https://github.com/italia/designers.italia.it/assets/6736103/26cbff7d-59c6-481c-a15b-90becd8a12f2)

2023-10-12 15:52 UTC, zetareticoli commented
@Fupete e @danielaiozzo Ho inserito le immagini mancanti e i contenuti relativi ad Anatomia e Specifiche.

Rimetto in review 😇

2023-10-12 16:17 UTC, Fupete commented
@zetareticoli ho passato le immagini alla versione ImgFull. Secondo me è decisamente meglio. Cosa ne pensi?

2023-10-12 16:36 UTC, Fupete approved these changes

2023-10-13 07:00 UTC, danielaiozzo submitted a review, later dismissed

2023-10-13 07:00 UTC, danielaiozzo commented on src/data/content/design-system/componenti/header.yaml
> +              È necessario utilizzare il componente header in cima ad ogni pagina di un sito o servizio digitale della pubblica amministrazione italiana.
```suggestion
              È necessario utilizzare il componente header in cima ad ogni pagina di un sito o servizio digitale della Pubblica Amministrazione italiana.
```

2023-10-13 07:00 UTC, danielaiozzo commented on src/data/content/design-system/componenti/header.yaml
> +              L’header centrale è una parte essenziale perché include il brand dell’ente e la sua descrizione. L’accesso al motore di ricerca e link aggiuntivi ai social medi completano il componente
```suggestion
              L’header centrale è una parte essenziale perché include il brand dell’ente e la sua descrizione. L’accesso al motore di ricerca e link aggiuntivi ai social media completano il componente.
```

2023-10-13 07:05 UTC, danielaiozzo commented on src/data/content/design-system/componenti/header.yaml
> +              Lo _slim header_ è una porzione dell'header più **compatta** e **flessibile** che può indicare l'appartenenza del sito o servizio a una categoria o a un ordine gerarchico.
```suggestion
              Lo slim header è una porzione dell'header più **compatta** e **flessibile** che può indicare l'appartenenza del sito o servizio a una categoria o a un ordine gerarchico.  
```

2023-10-13 08:03 UTC, Fupete commented
> > @zetareticoli ho passato le immagini alla versione ImgFull. Secondo me è decisamente meglio. Cosa ne pensi?
> > ps. potremmo usare questo approccio per i componenti giustamente "larghi" (eg. Footer, Hero, Header, ...) e lasciare in colonna (immagine markdown) tutti gli altri.
> 
> Sì va decisamente meglio. Ci sono dei piccoli bug di renderizzazione dei bordi delle immagini, vengono come tagliati (sia lato superiore che laterale). Dipende forse dal resize automatico?

Sì è dovuto alla renderizzazione, quel bordo di 1 solo px probabilmente dovremmo metterlo via css e non nelle immagini. Pensiamoci senza fretta, al massimo si ri-esportano e sostituiscono tutte insieme alla fine.

2023-10-13 08:38 UTC, danielaiozzo requested changes

2023-10-13 08:38 UTC, danielaiozzo commented on src/data/content/design-system/componenti/header.yaml
> +              - **pagina di login/registrazione**, consente alle persone di concentrarsi sull’azione primaria;
```suggestion
              - **pagina di login/registrazione**: consente alle persone di concentrarsi sull’azione primaria;
```

2023-10-13 08:38 UTC, danielaiozzo commented on src/data/content/design-system/componenti/header.yaml
> +              - **applicazioni di terze parti**, può essere utilizzato nelle schermate in cui è necessario mostrare solo un titolo o un'icona di ritorno alla schermata precedente, riducendo al minimo
```suggestion
              - **applicazioni di terze parti**: può essere utilizzato nelle schermate in cui è necessario mostrare solo un titolo o un'icona di ritorno alla schermata precedente, riducendo al minimo la presenza di elementi di navigazione;
```

2023-10-13 08:38 UTC, danielaiozzo commented on src/data/content/design-system/componenti/header.yaml
> +              - **dashboard o pannelli di controllo**, in un ambiente di amministrazione, l'header slim può contenere informazioni chiave come il nome dell'utente, le notifiche e l'accesso rapido all
```suggestion
              - **dashboard o pannelli di controllo**: in un ambiente di amministrazione, l'header slim può contenere informazioni chiave come il nome dell'utente, le notifiche e l'accesso rapido alle funzionalità principali, contribuendo a mantenere la vista generale del dashboard più pulita e concentrata.
```

2023-10-13 08:38 UTC, danielaiozzo commented on src/data/content/design-system/componenti/header.yaml
> +              - **pagine di contenuto focalizzato**, come articoli o pagine di prodotto, nelle quali l’header slim mantiene informazioni di navigazione essenziali;
```suggestion
              - **pagine di contenuto focalizzato**: es. articoli o pagine di prodotto, nelle quali l’header slim mantiene informazioni di navigazione essenziali;
```

2023-10-13 08:51 UTC, Fupete commented
> > > @zetareticoli ho passato le immagini alla versione ImgFull. Secondo me è decisamente meglio. Cosa ne pensi?
> > > ps. potremmo usare questo approccio per i componenti giustamente "larghi" (eg. Footer, Hero, Header, ...) e lasciare in colonna (immagine markdown) tutti gli altri.
> > 
> > 
> > Sì va decisamente meglio. Ci sono dei piccoli bug di renderizzazione dei bordi delle immagini, vengono come tagliati (sia lato superiore che laterale). Dipende forse dal resize automatico?
> 
> Sì è dovuto alla renderizzazione, quel bordo di 1 solo px probabilmente dovremmo metterlo via css e non nelle immagini. Pensiamoci senza fretta, al massimo si ri-esportano e sostituiscono tutte insieme alla fine.

@zetareticoli ho appena "committato" una modifica che mette bordo e arrotondamento via css intanto a queste ImgFull. Dai un'occhiata. Secondo me meglio così.

2023-10-13 09:13 UTC, danielaiozzo approved these changes

2023-10-13 09:42 UTC, merged