chore: deps and examples update
italia/designers.italia.it pull request #899
Opened 2023-09-26 13:09 UTC by astagi

2023-09-27 11:41 UTC, Fupete commented
✅ @astagi I have added a background color fix to the iframes for all the examples 

⚠️ @astagi @zetareticoli but the typography of the website goes a little weird with this BSI 2.7.0 update. At least at a first approach we have some wrong changes from sans-serif to serif in intro secrtions, and some too little little font sizes around cards (12, 13, 14...). Let's review them live if you need.

2023-09-27 11:42 UTC, Fupete requested changes
See https://github.com/italia/designers.italia.it/pull/899#issuecomment-1737228900

2023-09-27 11:53 UTC, zetareticoli commented
> ✅ @astagi I have added a background color fix to the iframes for all the examples
> 
> ⚠️ @astagi @zetareticoli but the typography of the website goes a little weird with this BSI 2.7.0 update. At least at a first approach we have some wrong changes from sans-serif to serif in intro secrtions, some too little little font sizes around cards and elsewhere (12, 13, 14...), and also un-centered and un-spaced chips. Let's review them live if you need.

there are some project's custom declarations like:

```css
.di-card .text-zone p {
   font-size: var(--card-p-size); // 0.8888888888888rem
}
```

that affect the final result. We should take a look to every single one and decide what remove.

2023-09-27 11:56 UTC, Fupete commented
> > ✅ @astagi I have added a background color fix to the iframes for all the examples
> > ⚠️ @astagi @zetareticoli but the typography of the website goes a little weird with this BSI 2.7.0 update. At least at a first approach we have some wrong changes from sans-serif to serif in intro secrtions, some too little little font sizes around cards and elsewhere (12, 13, 14...), and also un-centered and un-spaced chips. Let's review them live if you need.
> 
> there are some project's custom declarations like:
> 
> ```css
> .di-card .text-zone p {
>    font-size: var(--card-p-size); // 0.8888888888888rem
> }
> ```
> 
> that affect the final result. We should take a look at every single one and decide what to remove.

Yes I agree. It cannot be not a quick update. We have to refactor here and there things before to merge: there are little font sizes, wrong fonts, and too tiny spaces everywhere (menu, footer lists, cards, intros, ...) 🤷‍♂️ 😮‍💨

2023-10-02 16:04 UTC, Fupete commented
Waiting for BSI fixes in 2.8... cc @zetareticoli @astagi

2023-10-02 16:40 UTC, Fupete commented
@zetareticoli @astagi added more fixes [here](https://github.com/italia/designers.italia.it/pull/899/commits/43e99b4ec6f3c988d5c385abb78af6f3fcd554cc) because we have used more <small> on the archive lists...

2023-10-05 14:32 UTC, Fupete approved these changes
Seems fine to me. @bfabio wdyt?

2023-10-05 15:01 UTC, bfabio reviewed
LGTM, it can be merged after fixing the failing tests

2023-10-06 10:31 UTC, bfabio commented on src/components/last-update/last-update.js
> +                      addonClasses="mb-1"
```suggestion
                    addonClasses="mb-1"
```

2023-10-06 11:31 UTC, bfabio approved these changes

2023-10-06 11:31 UTC, merged

2023-10-06 11:32 UTC, Fupete commented
👏