content: new pages modelli
italia/designers.italia.it pull request #920
Opened 2023-10-04 14:50 UTC by Fupete

2023-10-27 11:16 UTC, Fupete commented on src/data/content/modelli.yaml
> +          url: "musei/" #M
```suggestion
          url: "musei-civici/" #M
```

2023-11-14 09:21 UTC, Fupete commented
@danielenole @danielaiozzo this is ready for me. Do your final review and we will merge it today. Thanks.

2023-11-14 10:04 UTC, danielaiozzo requested changes
minor suggestions

2023-11-14 10:04 UTC, danielaiozzo commented on src/data/content/modelli/musei-civici.yaml
> +  description: A breve tutte le risorse per realizzare con facilità esperienze digitali semplici e accessibili per i visitatori dei musei civici #C
```suggestion
  description: Presto disponibili le risorse per realizzare con facilità esperienze digitali semplici e accessibili per i visitatori dei musei civici #C
```

2023-11-14 10:04 UTC, danielaiozzo commented on src/data/content/modelli/musei-civici.yaml
> +    subtitle: A breve tutte le risorse per realizzare con facilità esperienze digitali semplici e accessibili per i visitatori dei musei civici #C
```suggestion
    subtitle: Presto disponibili le risorse per realizzare con facilità esperienze digitali semplici e accessibili per i visitatori dei musei civici #C
```

2023-11-14 10:04 UTC, danielaiozzo commented on src/data/content/modelli/musei-civici.yaml
> +      Il modello, ora in lavorazione, ti permette di **realizzare siti dei musei civici** già validati dalla ricerca e progettati sui bisogni degli utenti, in modo rapido ed economico. Scopri tutti g
```suggestion
      Il modello, ora in lavorazione, ti permette di **realizzare siti dei musei civici** già validati dalla ricerca e progettati sui bisogni degli utenti, in modo rapido ed economico. Scopri tutti gli aggiornamenti sul modello, il processo di progettazione e le risorse in arrivo. 
```

2023-11-14 10:24 UTC, danielaiozzo approved these changes

2023-11-14 10:51 UTC, danielenole approved these changes

2023-11-14 11:25 UTC, merged